/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals;


import NewcastleConnections.packagedeals.tables.Experiencebookingoffering;
import NewcastleConnections.packagedeals.tables.Experienceofferingdates;
import NewcastleConnections.packagedeals.tables.Experienceofferingsdatetime;
import NewcastleConnections.packagedeals.tables.Experienceproviders;
import NewcastleConnections.packagedeals.tables.Experiences;
import NewcastleConnections.packagedeals.tables.Experiencevoucherofferings;
import NewcastleConnections.packagedeals.tables.Hotels;
import NewcastleConnections.packagedeals.tables.Invoiceexperience;
import NewcastleConnections.packagedeals.tables.Invoicehotel;
import NewcastleConnections.packagedeals.tables.Invoicerestaurant;
import NewcastleConnections.packagedeals.tables.Invoices;
import NewcastleConnections.packagedeals.tables.Invoicestatus;
import NewcastleConnections.packagedeals.tables.Invoicetransport;
import NewcastleConnections.packagedeals.tables.Resturantopeninghours;
import NewcastleConnections.packagedeals.tables.Resturantopeninghoursoverrides;
import NewcastleConnections.packagedeals.tables.Resturantreservationofferingoverrides;
import NewcastleConnections.packagedeals.tables.Resturantreservationofferings;
import NewcastleConnections.packagedeals.tables.Resturants;
import NewcastleConnections.packagedeals.tables.Roomofferingallocations;
import NewcastleConnections.packagedeals.tables.Roomofferingrateoverrides;
import NewcastleConnections.packagedeals.tables.Roomofferingrates;
import NewcastleConnections.packagedeals.tables.Roomofferings;
import NewcastleConnections.packagedeals.tables.Roomtypes;
import NewcastleConnections.packagedeals.tables.Tags;
import NewcastleConnections.packagedeals.tables.Transport;
import NewcastleConnections.packagedeals.tables.Users;
import NewcastleConnections.packagedeals.tables.Weekday;
import NewcastleConnections.packagedeals.tables.records.ExperiencebookingofferingRecord;
import NewcastleConnections.packagedeals.tables.records.ExperienceofferingdatesRecord;
import NewcastleConnections.packagedeals.tables.records.ExperienceofferingsdatetimeRecord;
import NewcastleConnections.packagedeals.tables.records.ExperienceprovidersRecord;
import NewcastleConnections.packagedeals.tables.records.ExperiencesRecord;
import NewcastleConnections.packagedeals.tables.records.ExperiencevoucherofferingsRecord;
import NewcastleConnections.packagedeals.tables.records.HotelsRecord;
import NewcastleConnections.packagedeals.tables.records.InvoiceexperienceRecord;
import NewcastleConnections.packagedeals.tables.records.InvoicehotelRecord;
import NewcastleConnections.packagedeals.tables.records.InvoicerestaurantRecord;
import NewcastleConnections.packagedeals.tables.records.InvoicesRecord;
import NewcastleConnections.packagedeals.tables.records.InvoicestatusRecord;
import NewcastleConnections.packagedeals.tables.records.InvoicetransportRecord;
import NewcastleConnections.packagedeals.tables.records.ResturantopeninghoursRecord;
import NewcastleConnections.packagedeals.tables.records.ResturantopeninghoursoverridesRecord;
import NewcastleConnections.packagedeals.tables.records.ResturantreservationofferingoverridesRecord;
import NewcastleConnections.packagedeals.tables.records.ResturantreservationofferingsRecord;
import NewcastleConnections.packagedeals.tables.records.ResturantsRecord;
import NewcastleConnections.packagedeals.tables.records.RoomofferingallocationsRecord;
import NewcastleConnections.packagedeals.tables.records.RoomofferingrateoverridesRecord;
import NewcastleConnections.packagedeals.tables.records.RoomofferingratesRecord;
import NewcastleConnections.packagedeals.tables.records.RoomofferingsRecord;
import NewcastleConnections.packagedeals.tables.records.RoomtypesRecord;
import NewcastleConnections.packagedeals.tables.records.TagsRecord;
import NewcastleConnections.packagedeals.tables.records.TransportRecord;
import NewcastleConnections.packagedeals.tables.records.UsersRecord;
import NewcastleConnections.packagedeals.tables.records.WeekdayRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships between tables of the <code>PackageDeals</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ExperiencebookingofferingRecord, UInteger> IDENTITY_EXPERIENCEBOOKINGOFFERING = Identities0.IDENTITY_EXPERIENCEBOOKINGOFFERING;
    public static final Identity<ExperienceofferingdatesRecord, UInteger> IDENTITY_EXPERIENCEOFFERINGDATES = Identities0.IDENTITY_EXPERIENCEOFFERINGDATES;
    public static final Identity<ExperienceofferingsdatetimeRecord, UInteger> IDENTITY_EXPERIENCEOFFERINGSDATETIME = Identities0.IDENTITY_EXPERIENCEOFFERINGSDATETIME;
    public static final Identity<ExperienceprovidersRecord, UInteger> IDENTITY_EXPERIENCEPROVIDERS = Identities0.IDENTITY_EXPERIENCEPROVIDERS;
    public static final Identity<ExperiencesRecord, UInteger> IDENTITY_EXPERIENCES = Identities0.IDENTITY_EXPERIENCES;
    public static final Identity<ExperiencevoucherofferingsRecord, UInteger> IDENTITY_EXPERIENCEVOUCHEROFFERINGS = Identities0.IDENTITY_EXPERIENCEVOUCHEROFFERINGS;
    public static final Identity<HotelsRecord, UInteger> IDENTITY_HOTELS = Identities0.IDENTITY_HOTELS;
    public static final Identity<InvoicesRecord, UInteger> IDENTITY_INVOICES = Identities0.IDENTITY_INVOICES;
    public static final Identity<ResturantopeninghoursRecord, UInteger> IDENTITY_RESTURANTOPENINGHOURS = Identities0.IDENTITY_RESTURANTOPENINGHOURS;
    public static final Identity<ResturantopeninghoursoverridesRecord, UInteger> IDENTITY_RESTURANTOPENINGHOURSOVERRIDES = Identities0.IDENTITY_RESTURANTOPENINGHOURSOVERRIDES;
    public static final Identity<ResturantreservationofferingoverridesRecord, UInteger> IDENTITY_RESTURANTRESERVATIONOFFERINGOVERRIDES = Identities0.IDENTITY_RESTURANTRESERVATIONOFFERINGOVERRIDES;
    public static final Identity<ResturantreservationofferingsRecord, UInteger> IDENTITY_RESTURANTRESERVATIONOFFERINGS = Identities0.IDENTITY_RESTURANTRESERVATIONOFFERINGS;
    public static final Identity<ResturantsRecord, UInteger> IDENTITY_RESTURANTS = Identities0.IDENTITY_RESTURANTS;
    public static final Identity<RoomofferingallocationsRecord, UInteger> IDENTITY_ROOMOFFERINGALLOCATIONS = Identities0.IDENTITY_ROOMOFFERINGALLOCATIONS;
    public static final Identity<RoomofferingrateoverridesRecord, UInteger> IDENTITY_ROOMOFFERINGRATEOVERRIDES = Identities0.IDENTITY_ROOMOFFERINGRATEOVERRIDES;
    public static final Identity<RoomofferingratesRecord, UInteger> IDENTITY_ROOMOFFERINGRATES = Identities0.IDENTITY_ROOMOFFERINGRATES;
    public static final Identity<RoomofferingsRecord, UInteger> IDENTITY_ROOMOFFERINGS = Identities0.IDENTITY_ROOMOFFERINGS;
    public static final Identity<RoomtypesRecord, UInteger> IDENTITY_ROOMTYPES = Identities0.IDENTITY_ROOMTYPES;
    public static final Identity<TagsRecord, Integer> IDENTITY_TAGS = Identities0.IDENTITY_TAGS;
    public static final Identity<TransportRecord, UInteger> IDENTITY_TRANSPORT = Identities0.IDENTITY_TRANSPORT;
    public static final Identity<WeekdayRecord, UInteger> IDENTITY_WEEKDAY = Identities0.IDENTITY_WEEKDAY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ExperiencebookingofferingRecord> KEY_EXPERIENCEBOOKINGOFFERING_PRIMARY = UniqueKeys0.KEY_EXPERIENCEBOOKINGOFFERING_PRIMARY;
    public static final UniqueKey<ExperienceofferingdatesRecord> KEY_EXPERIENCEOFFERINGDATES_PRIMARY = UniqueKeys0.KEY_EXPERIENCEOFFERINGDATES_PRIMARY;
    public static final UniqueKey<ExperienceofferingsdatetimeRecord> KEY_EXPERIENCEOFFERINGSDATETIME_PRIMARY = UniqueKeys0.KEY_EXPERIENCEOFFERINGSDATETIME_PRIMARY;
    public static final UniqueKey<ExperienceprovidersRecord> KEY_EXPERIENCEPROVIDERS_PRIMARY = UniqueKeys0.KEY_EXPERIENCEPROVIDERS_PRIMARY;
    public static final UniqueKey<ExperiencesRecord> KEY_EXPERIENCES_PRIMARY = UniqueKeys0.KEY_EXPERIENCES_PRIMARY;
    public static final UniqueKey<ExperiencevoucherofferingsRecord> KEY_EXPERIENCEVOUCHEROFFERINGS_PRIMARY = UniqueKeys0.KEY_EXPERIENCEVOUCHEROFFERINGS_PRIMARY;
    public static final UniqueKey<HotelsRecord> KEY_HOTELS_PRIMARY = UniqueKeys0.KEY_HOTELS_PRIMARY;
    public static final UniqueKey<InvoiceexperienceRecord> KEY_INVOICEEXPERIENCE_PRIMARY = UniqueKeys0.KEY_INVOICEEXPERIENCE_PRIMARY;
    public static final UniqueKey<InvoicehotelRecord> KEY_INVOICEHOTEL_PRIMARY = UniqueKeys0.KEY_INVOICEHOTEL_PRIMARY;
    public static final UniqueKey<InvoicerestaurantRecord> KEY_INVOICERESTAURANT_PRIMARY = UniqueKeys0.KEY_INVOICERESTAURANT_PRIMARY;
    public static final UniqueKey<InvoicesRecord> KEY_INVOICES_PRIMARY = UniqueKeys0.KEY_INVOICES_PRIMARY;
    public static final UniqueKey<InvoicestatusRecord> KEY_INVOICESTATUS_PRIMARY = UniqueKeys0.KEY_INVOICESTATUS_PRIMARY;
    public static final UniqueKey<InvoicetransportRecord> KEY_INVOICETRANSPORT_PRIMARY = UniqueKeys0.KEY_INVOICETRANSPORT_PRIMARY;
    public static final UniqueKey<ResturantopeninghoursRecord> KEY_RESTURANTOPENINGHOURS_PRIMARY = UniqueKeys0.KEY_RESTURANTOPENINGHOURS_PRIMARY;
    public static final UniqueKey<ResturantopeninghoursoverridesRecord> KEY_RESTURANTOPENINGHOURSOVERRIDES_PRIMARY = UniqueKeys0.KEY_RESTURANTOPENINGHOURSOVERRIDES_PRIMARY;
    public static final UniqueKey<ResturantopeninghoursoverridesRecord> KEY_RESTURANTOPENINGHOURSOVERRIDES_UQ_RESTURANTID_DATE = UniqueKeys0.KEY_RESTURANTOPENINGHOURSOVERRIDES_UQ_RESTURANTID_DATE;
    public static final UniqueKey<ResturantreservationofferingoverridesRecord> KEY_RESTURANTRESERVATIONOFFERINGOVERRIDES_PRIMARY = UniqueKeys0.KEY_RESTURANTRESERVATIONOFFERINGOVERRIDES_PRIMARY;
    public static final UniqueKey<ResturantreservationofferingsRecord> KEY_RESTURANTRESERVATIONOFFERINGS_PRIMARY = UniqueKeys0.KEY_RESTURANTRESERVATIONOFFERINGS_PRIMARY;
    public static final UniqueKey<ResturantsRecord> KEY_RESTURANTS_PRIMARY = UniqueKeys0.KEY_RESTURANTS_PRIMARY;
    public static final UniqueKey<RoomofferingallocationsRecord> KEY_ROOMOFFERINGALLOCATIONS_PRIMARY = UniqueKeys0.KEY_ROOMOFFERINGALLOCATIONS_PRIMARY;
    public static final UniqueKey<RoomofferingrateoverridesRecord> KEY_ROOMOFFERINGRATEOVERRIDES_PRIMARY = UniqueKeys0.KEY_ROOMOFFERINGRATEOVERRIDES_PRIMARY;
    public static final UniqueKey<RoomofferingratesRecord> KEY_ROOMOFFERINGRATES_PRIMARY = UniqueKeys0.KEY_ROOMOFFERINGRATES_PRIMARY;
    public static final UniqueKey<RoomofferingsRecord> KEY_ROOMOFFERINGS_PRIMARY = UniqueKeys0.KEY_ROOMOFFERINGS_PRIMARY;
    public static final UniqueKey<RoomtypesRecord> KEY_ROOMTYPES_PRIMARY = UniqueKeys0.KEY_ROOMTYPES_PRIMARY;
    public static final UniqueKey<TagsRecord> KEY_TAGS_PRIMARY = UniqueKeys0.KEY_TAGS_PRIMARY;
    public static final UniqueKey<TransportRecord> KEY_TRANSPORT_PRIMARY = UniqueKeys0.KEY_TRANSPORT_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
    public static final UniqueKey<WeekdayRecord> KEY_WEEKDAY_PRIMARY = UniqueKeys0.KEY_WEEKDAY_PRIMARY;
    public static final UniqueKey<WeekdayRecord> KEY_WEEKDAY_DAY_UNIQUE = UniqueKeys0.KEY_WEEKDAY_DAY_UNIQUE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ExperiencebookingofferingRecord, ExperiencesRecord> FK_EXPERIENCEBOOKINGOFFERING_EXPERIENCES = ForeignKeys0.FK_EXPERIENCEBOOKINGOFFERING_EXPERIENCES;
    public static final ForeignKey<ExperienceofferingdatesRecord, ExperiencebookingofferingRecord> FK_EXPERIENCEOFFERINGDATES_EXPERIENCES = ForeignKeys0.FK_EXPERIENCEOFFERINGDATES_EXPERIENCES;
    public static final ForeignKey<ExperienceofferingsdatetimeRecord, ExperienceofferingdatesRecord> FK_EXPERIENCEOFFERINGSDATETIME = ForeignKeys0.FK_EXPERIENCEOFFERINGSDATETIME;
    public static final ForeignKey<ExperiencesRecord, ExperienceprovidersRecord> FK_EXPERIENCES_EXPERIENCEPROVIDERS = ForeignKeys0.FK_EXPERIENCES_EXPERIENCEPROVIDERS;
    public static final ForeignKey<ExperiencevoucherofferingsRecord, ExperiencesRecord> FK_EXPERIENCEVOUCHEROFFERINGS_EXPERIENCES = ForeignKeys0.FK_EXPERIENCEVOUCHEROFFERINGS_EXPERIENCES;
    public static final ForeignKey<InvoiceexperienceRecord, InvoicesRecord> IEINVOICE = ForeignKeys0.IEINVOICE;
    public static final ForeignKey<InvoiceexperienceRecord, ExperiencevoucherofferingsRecord> IEVOUCHER = ForeignKeys0.IEVOUCHER;
    public static final ForeignKey<InvoicehotelRecord, InvoicesRecord> IHINVOICE = ForeignKeys0.IHINVOICE;
    public static final ForeignKey<InvoicehotelRecord, RoomofferingsRecord> IHROOM = ForeignKeys0.IHROOM;
    public static final ForeignKey<InvoicerestaurantRecord, InvoicesRecord> IRINVOICE = ForeignKeys0.IRINVOICE;
    public static final ForeignKey<InvoicerestaurantRecord, ResturantsRecord> IRRESTAURANT = ForeignKeys0.IRRESTAURANT;
    public static final ForeignKey<InvoicetransportRecord, InvoicesRecord> ITINVOICE = ForeignKeys0.ITINVOICE;
    public static final ForeignKey<InvoicetransportRecord, TransportRecord> ITTRANSPORT = ForeignKeys0.ITTRANSPORT;
    public static final ForeignKey<ResturantopeninghoursRecord, WeekdayRecord> FK_RESTURANTOPENINGHOURS_WEEKDAY = ForeignKeys0.FK_RESTURANTOPENINGHOURS_WEEKDAY;
    public static final ForeignKey<ResturantopeninghoursoverridesRecord, ResturantsRecord> FK_RESTURANTOPENINGHOURSOVERRIDES_RESTURANTS = ForeignKeys0.FK_RESTURANTOPENINGHOURSOVERRIDES_RESTURANTS;
    public static final ForeignKey<ResturantreservationofferingoverridesRecord, ResturantsRecord> FK_RESTURANTRESERVATIONOFFERINGOVERRIDES_RESTURANTS = ForeignKeys0.FK_RESTURANTRESERVATIONOFFERINGOVERRIDES_RESTURANTS;
    public static final ForeignKey<ResturantreservationofferingsRecord, WeekdayRecord> FK_RESTURANTRESERVATIONOFFERINGS_WEEKDAY = ForeignKeys0.FK_RESTURANTRESERVATIONOFFERINGS_WEEKDAY;
    public static final ForeignKey<ResturantreservationofferingsRecord, ResturantsRecord> FK_RESTURANTRESERVATIONOFFERINGS_RESTURANTS = ForeignKeys0.FK_RESTURANTRESERVATIONOFFERINGS_RESTURANTS;
    public static final ForeignKey<RoomofferingallocationsRecord, RoomofferingsRecord> FK_ROOMOFFERINGALLOCATION_ROOMOFFERING = ForeignKeys0.FK_ROOMOFFERINGALLOCATION_ROOMOFFERING;
    public static final ForeignKey<RoomofferingrateoverridesRecord, RoomofferingsRecord> FK_ROOMOFFERINGRATEOVERRIDE_ROOMOFFERING = ForeignKeys0.FK_ROOMOFFERINGRATEOVERRIDE_ROOMOFFERING;
    public static final ForeignKey<RoomofferingratesRecord, RoomofferingsRecord> FK_ROOMOFFERINGRATE_ROOMOFFERING = ForeignKeys0.FK_ROOMOFFERINGRATE_ROOMOFFERING;
    public static final ForeignKey<RoomofferingsRecord, HotelsRecord> FK_ROOMOFFERING_HOTEL = ForeignKeys0.FK_ROOMOFFERING_HOTEL;
    public static final ForeignKey<RoomofferingsRecord, RoomtypesRecord> FK_ROOMOFFERING_ROOMTYPE = ForeignKeys0.FK_ROOMOFFERING_ROOMTYPE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ExperiencebookingofferingRecord, UInteger> IDENTITY_EXPERIENCEBOOKINGOFFERING = createIdentity(Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING, Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING.ID);
        public static Identity<ExperienceofferingdatesRecord, UInteger> IDENTITY_EXPERIENCEOFFERINGDATES = createIdentity(Experienceofferingdates.EXPERIENCEOFFERINGDATES, Experienceofferingdates.EXPERIENCEOFFERINGDATES.ID);
        public static Identity<ExperienceofferingsdatetimeRecord, UInteger> IDENTITY_EXPERIENCEOFFERINGSDATETIME = createIdentity(Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME, Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME.ID);
        public static Identity<ExperienceprovidersRecord, UInteger> IDENTITY_EXPERIENCEPROVIDERS = createIdentity(Experienceproviders.EXPERIENCEPROVIDERS, Experienceproviders.EXPERIENCEPROVIDERS.ID);
        public static Identity<ExperiencesRecord, UInteger> IDENTITY_EXPERIENCES = createIdentity(Experiences.EXPERIENCES, Experiences.EXPERIENCES.ID);
        public static Identity<ExperiencevoucherofferingsRecord, UInteger> IDENTITY_EXPERIENCEVOUCHEROFFERINGS = createIdentity(Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS, Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS.ID);
        public static Identity<HotelsRecord, UInteger> IDENTITY_HOTELS = createIdentity(Hotels.HOTELS, Hotels.HOTELS.ID);
        public static Identity<InvoicesRecord, UInteger> IDENTITY_INVOICES = createIdentity(Invoices.INVOICES, Invoices.INVOICES.ID);
        public static Identity<ResturantopeninghoursRecord, UInteger> IDENTITY_RESTURANTOPENINGHOURS = createIdentity(Resturantopeninghours.RESTURANTOPENINGHOURS, Resturantopeninghours.RESTURANTOPENINGHOURS.ID);
        public static Identity<ResturantopeninghoursoverridesRecord, UInteger> IDENTITY_RESTURANTOPENINGHOURSOVERRIDES = createIdentity(Resturantopeninghoursoverrides.RESTURANTOPENINGHOURSOVERRIDES, Resturantopeninghoursoverrides.RESTURANTOPENINGHOURSOVERRIDES.ID);
        public static Identity<ResturantreservationofferingoverridesRecord, UInteger> IDENTITY_RESTURANTRESERVATIONOFFERINGOVERRIDES = createIdentity(Resturantreservationofferingoverrides.RESTURANTRESERVATIONOFFERINGOVERRIDES, Resturantreservationofferingoverrides.RESTURANTRESERVATIONOFFERINGOVERRIDES.ID);
        public static Identity<ResturantreservationofferingsRecord, UInteger> IDENTITY_RESTURANTRESERVATIONOFFERINGS = createIdentity(Resturantreservationofferings.RESTURANTRESERVATIONOFFERINGS, Resturantreservationofferings.RESTURANTRESERVATIONOFFERINGS.ID);
        public static Identity<ResturantsRecord, UInteger> IDENTITY_RESTURANTS = createIdentity(Resturants.RESTURANTS, Resturants.RESTURANTS.ID);
        public static Identity<RoomofferingallocationsRecord, UInteger> IDENTITY_ROOMOFFERINGALLOCATIONS = createIdentity(Roomofferingallocations.ROOMOFFERINGALLOCATIONS, Roomofferingallocations.ROOMOFFERINGALLOCATIONS.ID);
        public static Identity<RoomofferingrateoverridesRecord, UInteger> IDENTITY_ROOMOFFERINGRATEOVERRIDES = createIdentity(Roomofferingrateoverrides.ROOMOFFERINGRATEOVERRIDES, Roomofferingrateoverrides.ROOMOFFERINGRATEOVERRIDES.ID);
        public static Identity<RoomofferingratesRecord, UInteger> IDENTITY_ROOMOFFERINGRATES = createIdentity(Roomofferingrates.ROOMOFFERINGRATES, Roomofferingrates.ROOMOFFERINGRATES.ID);
        public static Identity<RoomofferingsRecord, UInteger> IDENTITY_ROOMOFFERINGS = createIdentity(Roomofferings.ROOMOFFERINGS, Roomofferings.ROOMOFFERINGS.ID);
        public static Identity<RoomtypesRecord, UInteger> IDENTITY_ROOMTYPES = createIdentity(Roomtypes.ROOMTYPES, Roomtypes.ROOMTYPES.ID);
        public static Identity<TagsRecord, Integer> IDENTITY_TAGS = createIdentity(Tags.TAGS, Tags.TAGS.ID);
        public static Identity<TransportRecord, UInteger> IDENTITY_TRANSPORT = createIdentity(Transport.TRANSPORT, Transport.TRANSPORT.ID);
        public static Identity<WeekdayRecord, UInteger> IDENTITY_WEEKDAY = createIdentity(Weekday.WEEKDAY, Weekday.WEEKDAY.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ExperiencebookingofferingRecord> KEY_EXPERIENCEBOOKINGOFFERING_PRIMARY = createUniqueKey(Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING, "KEY_ExperienceBookingOffering_PRIMARY", Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING.ID);
        public static final UniqueKey<ExperienceofferingdatesRecord> KEY_EXPERIENCEOFFERINGDATES_PRIMARY = createUniqueKey(Experienceofferingdates.EXPERIENCEOFFERINGDATES, "KEY_ExperienceOfferingDates_PRIMARY", Experienceofferingdates.EXPERIENCEOFFERINGDATES.ID);
        public static final UniqueKey<ExperienceofferingsdatetimeRecord> KEY_EXPERIENCEOFFERINGSDATETIME_PRIMARY = createUniqueKey(Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME, "KEY_ExperienceOfferingsDateTime_PRIMARY", Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME.ID);
        public static final UniqueKey<ExperienceprovidersRecord> KEY_EXPERIENCEPROVIDERS_PRIMARY = createUniqueKey(Experienceproviders.EXPERIENCEPROVIDERS, "KEY_ExperienceProviders_PRIMARY", Experienceproviders.EXPERIENCEPROVIDERS.ID);
        public static final UniqueKey<ExperiencesRecord> KEY_EXPERIENCES_PRIMARY = createUniqueKey(Experiences.EXPERIENCES, "KEY_Experiences_PRIMARY", Experiences.EXPERIENCES.ID);
        public static final UniqueKey<ExperiencevoucherofferingsRecord> KEY_EXPERIENCEVOUCHEROFFERINGS_PRIMARY = createUniqueKey(Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS, "KEY_ExperienceVoucherOfferings_PRIMARY", Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS.ID);
        public static final UniqueKey<HotelsRecord> KEY_HOTELS_PRIMARY = createUniqueKey(Hotels.HOTELS, "KEY_Hotels_PRIMARY", Hotels.HOTELS.ID);
        public static final UniqueKey<InvoiceexperienceRecord> KEY_INVOICEEXPERIENCE_PRIMARY = createUniqueKey(Invoiceexperience.INVOICEEXPERIENCE, "KEY_InvoiceExperience_PRIMARY", Invoiceexperience.INVOICEEXPERIENCE.INVOICEID, Invoiceexperience.INVOICEEXPERIENCE.EXPERIENCEVOUCHERID);
        public static final UniqueKey<InvoicehotelRecord> KEY_INVOICEHOTEL_PRIMARY = createUniqueKey(Invoicehotel.INVOICEHOTEL, "KEY_InvoiceHotel_PRIMARY", Invoicehotel.INVOICEHOTEL.INVOICEID, Invoicehotel.INVOICEHOTEL.ROOMID);
        public static final UniqueKey<InvoicerestaurantRecord> KEY_INVOICERESTAURANT_PRIMARY = createUniqueKey(Invoicerestaurant.INVOICERESTAURANT, "KEY_InvoiceRestaurant_PRIMARY", Invoicerestaurant.INVOICERESTAURANT.INVOICEID, Invoicerestaurant.INVOICERESTAURANT.RESTAURANTID);
        public static final UniqueKey<InvoicesRecord> KEY_INVOICES_PRIMARY = createUniqueKey(Invoices.INVOICES, "KEY_Invoices_PRIMARY", Invoices.INVOICES.ID);
        public static final UniqueKey<InvoicestatusRecord> KEY_INVOICESTATUS_PRIMARY = createUniqueKey(Invoicestatus.INVOICESTATUS, "KEY_InvoiceStatus_PRIMARY", Invoicestatus.INVOICESTATUS.ID);
        public static final UniqueKey<InvoicetransportRecord> KEY_INVOICETRANSPORT_PRIMARY = createUniqueKey(Invoicetransport.INVOICETRANSPORT, "KEY_InvoiceTransport_PRIMARY", Invoicetransport.INVOICETRANSPORT.INVOICEID, Invoicetransport.INVOICETRANSPORT.TRANSPORTID);
        public static final UniqueKey<ResturantopeninghoursRecord> KEY_RESTURANTOPENINGHOURS_PRIMARY = createUniqueKey(Resturantopeninghours.RESTURANTOPENINGHOURS, "KEY_ResturantOpeningHours_PRIMARY", Resturantopeninghours.RESTURANTOPENINGHOURS.ID);
        public static final UniqueKey<ResturantopeninghoursoverridesRecord> KEY_RESTURANTOPENINGHOURSOVERRIDES_PRIMARY = createUniqueKey(Resturantopeninghoursoverrides.RESTURANTOPENINGHOURSOVERRIDES, "KEY_ResturantOpeningHoursOverrides_PRIMARY", Resturantopeninghoursoverrides.RESTURANTOPENINGHOURSOVERRIDES.ID);
        public static final UniqueKey<ResturantopeninghoursoverridesRecord> KEY_RESTURANTOPENINGHOURSOVERRIDES_UQ_RESTURANTID_DATE = createUniqueKey(Resturantopeninghoursoverrides.RESTURANTOPENINGHOURSOVERRIDES, "KEY_ResturantOpeningHoursOverrides_uq_resturantId_date", Resturantopeninghoursoverrides.RESTURANTOPENINGHOURSOVERRIDES.DATE, Resturantopeninghoursoverrides.RESTURANTOPENINGHOURSOVERRIDES.RESTURANTID);
        public static final UniqueKey<ResturantreservationofferingoverridesRecord> KEY_RESTURANTRESERVATIONOFFERINGOVERRIDES_PRIMARY = createUniqueKey(Resturantreservationofferingoverrides.RESTURANTRESERVATIONOFFERINGOVERRIDES, "KEY_ResturantReservationOfferingOverrides_PRIMARY", Resturantreservationofferingoverrides.RESTURANTRESERVATIONOFFERINGOVERRIDES.ID);
        public static final UniqueKey<ResturantreservationofferingsRecord> KEY_RESTURANTRESERVATIONOFFERINGS_PRIMARY = createUniqueKey(Resturantreservationofferings.RESTURANTRESERVATIONOFFERINGS, "KEY_ResturantReservationOfferings_PRIMARY", Resturantreservationofferings.RESTURANTRESERVATIONOFFERINGS.ID);
        public static final UniqueKey<ResturantsRecord> KEY_RESTURANTS_PRIMARY = createUniqueKey(Resturants.RESTURANTS, "KEY_Resturants_PRIMARY", Resturants.RESTURANTS.ID);
        public static final UniqueKey<RoomofferingallocationsRecord> KEY_ROOMOFFERINGALLOCATIONS_PRIMARY = createUniqueKey(Roomofferingallocations.ROOMOFFERINGALLOCATIONS, "KEY_RoomOfferingAllocations_PRIMARY", Roomofferingallocations.ROOMOFFERINGALLOCATIONS.ID);
        public static final UniqueKey<RoomofferingrateoverridesRecord> KEY_ROOMOFFERINGRATEOVERRIDES_PRIMARY = createUniqueKey(Roomofferingrateoverrides.ROOMOFFERINGRATEOVERRIDES, "KEY_RoomOfferingRateOverrides_PRIMARY", Roomofferingrateoverrides.ROOMOFFERINGRATEOVERRIDES.ID);
        public static final UniqueKey<RoomofferingratesRecord> KEY_ROOMOFFERINGRATES_PRIMARY = createUniqueKey(Roomofferingrates.ROOMOFFERINGRATES, "KEY_RoomOfferingRates_PRIMARY", Roomofferingrates.ROOMOFFERINGRATES.ID);
        public static final UniqueKey<RoomofferingsRecord> KEY_ROOMOFFERINGS_PRIMARY = createUniqueKey(Roomofferings.ROOMOFFERINGS, "KEY_RoomOfferings_PRIMARY", Roomofferings.ROOMOFFERINGS.ID);
        public static final UniqueKey<RoomtypesRecord> KEY_ROOMTYPES_PRIMARY = createUniqueKey(Roomtypes.ROOMTYPES, "KEY_RoomTypes_PRIMARY", Roomtypes.ROOMTYPES.ID);
        public static final UniqueKey<TagsRecord> KEY_TAGS_PRIMARY = createUniqueKey(Tags.TAGS, "KEY_Tags_PRIMARY", Tags.TAGS.ID);
        public static final UniqueKey<TransportRecord> KEY_TRANSPORT_PRIMARY = createUniqueKey(Transport.TRANSPORT, "KEY_Transport_PRIMARY", Transport.TRANSPORT.ID);
        public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = createUniqueKey(Users.USERS, "KEY_Users_PRIMARY", Users.USERS.USERID);
        public static final UniqueKey<WeekdayRecord> KEY_WEEKDAY_PRIMARY = createUniqueKey(Weekday.WEEKDAY, "KEY_Weekday_PRIMARY", Weekday.WEEKDAY.ID);
        public static final UniqueKey<WeekdayRecord> KEY_WEEKDAY_DAY_UNIQUE = createUniqueKey(Weekday.WEEKDAY, "KEY_Weekday_day_UNIQUE", Weekday.WEEKDAY.DAY);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<ExperiencebookingofferingRecord, ExperiencesRecord> FK_EXPERIENCEBOOKINGOFFERING_EXPERIENCES = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_EXPERIENCES_PRIMARY, Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING, "fk_ExperienceBookingOffering_Experiences", Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING.EXPERIENCEID);
        public static final ForeignKey<ExperienceofferingdatesRecord, ExperiencebookingofferingRecord> FK_EXPERIENCEOFFERINGDATES_EXPERIENCES = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_EXPERIENCEBOOKINGOFFERING_PRIMARY, Experienceofferingdates.EXPERIENCEOFFERINGDATES, "fk_ExperienceOfferingDates_Experiences", Experienceofferingdates.EXPERIENCEOFFERINGDATES.EXPERIENCEBOOKINGOFFERINGID);
        public static final ForeignKey<ExperienceofferingsdatetimeRecord, ExperienceofferingdatesRecord> FK_EXPERIENCEOFFERINGSDATETIME = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_EXPERIENCEOFFERINGDATES_PRIMARY, Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME, "fk_ExperienceOfferingsDateTime", Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME.EXPERIENCEOFFERINGDATEID);
        public static final ForeignKey<ExperiencesRecord, ExperienceprovidersRecord> FK_EXPERIENCES_EXPERIENCEPROVIDERS = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_EXPERIENCEPROVIDERS_PRIMARY, Experiences.EXPERIENCES, "fk_Experiences_ExperienceProviders", Experiences.EXPERIENCES.EXPERIENCEPROVIDERID);
        public static final ForeignKey<ExperiencevoucherofferingsRecord, ExperiencesRecord> FK_EXPERIENCEVOUCHEROFFERINGS_EXPERIENCES = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_EXPERIENCES_PRIMARY, Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS, "fk_ExperienceVoucherOfferings_Experiences", Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS.EXPERIENCEID);
        public static final ForeignKey<InvoiceexperienceRecord, InvoicesRecord> IEINVOICE = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_INVOICES_PRIMARY, Invoiceexperience.INVOICEEXPERIENCE, "IEInvoice", Invoiceexperience.INVOICEEXPERIENCE.INVOICEID);
        public static final ForeignKey<InvoiceexperienceRecord, ExperiencevoucherofferingsRecord> IEVOUCHER = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_EXPERIENCEVOUCHEROFFERINGS_PRIMARY, Invoiceexperience.INVOICEEXPERIENCE, "IEVoucher", Invoiceexperience.INVOICEEXPERIENCE.EXPERIENCEVOUCHERID);
        public static final ForeignKey<InvoicehotelRecord, InvoicesRecord> IHINVOICE = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_INVOICES_PRIMARY, Invoicehotel.INVOICEHOTEL, "IHInvoice", Invoicehotel.INVOICEHOTEL.INVOICEID);
        public static final ForeignKey<InvoicehotelRecord, RoomofferingsRecord> IHROOM = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_ROOMOFFERINGS_PRIMARY, Invoicehotel.INVOICEHOTEL, "IHRoom", Invoicehotel.INVOICEHOTEL.ROOMID);
        public static final ForeignKey<InvoicerestaurantRecord, InvoicesRecord> IRINVOICE = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_INVOICES_PRIMARY, Invoicerestaurant.INVOICERESTAURANT, "IRInvoice", Invoicerestaurant.INVOICERESTAURANT.INVOICEID);
        public static final ForeignKey<InvoicerestaurantRecord, ResturantsRecord> IRRESTAURANT = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_RESTURANTS_PRIMARY, Invoicerestaurant.INVOICERESTAURANT, "IRRestaurant", Invoicerestaurant.INVOICERESTAURANT.RESTAURANTID);
        public static final ForeignKey<InvoicetransportRecord, InvoicesRecord> ITINVOICE = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_INVOICES_PRIMARY, Invoicetransport.INVOICETRANSPORT, "ITInvoice", Invoicetransport.INVOICETRANSPORT.INVOICEID);
        public static final ForeignKey<InvoicetransportRecord, TransportRecord> ITTRANSPORT = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_TRANSPORT_PRIMARY, Invoicetransport.INVOICETRANSPORT, "ITTransport", Invoicetransport.INVOICETRANSPORT.TRANSPORTID);
        public static final ForeignKey<ResturantopeninghoursRecord, WeekdayRecord> FK_RESTURANTOPENINGHOURS_WEEKDAY = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_WEEKDAY_PRIMARY, Resturantopeninghours.RESTURANTOPENINGHOURS, "fk_ResturantOpeningHours_Weekday", Resturantopeninghours.RESTURANTOPENINGHOURS.WEEKDAY);
        public static final ForeignKey<ResturantopeninghoursoverridesRecord, ResturantsRecord> FK_RESTURANTOPENINGHOURSOVERRIDES_RESTURANTS = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_RESTURANTS_PRIMARY, Resturantopeninghoursoverrides.RESTURANTOPENINGHOURSOVERRIDES, "fk_ResturantOpeningHoursOverrides_Resturants", Resturantopeninghoursoverrides.RESTURANTOPENINGHOURSOVERRIDES.RESTURANTID);
        public static final ForeignKey<ResturantreservationofferingoverridesRecord, ResturantsRecord> FK_RESTURANTRESERVATIONOFFERINGOVERRIDES_RESTURANTS = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_RESTURANTS_PRIMARY, Resturantreservationofferingoverrides.RESTURANTRESERVATIONOFFERINGOVERRIDES, "fk_ResturantReservationOfferingOverrides_Resturants", Resturantreservationofferingoverrides.RESTURANTRESERVATIONOFFERINGOVERRIDES.RESTURANTID);
        public static final ForeignKey<ResturantreservationofferingsRecord, WeekdayRecord> FK_RESTURANTRESERVATIONOFFERINGS_WEEKDAY = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_WEEKDAY_PRIMARY, Resturantreservationofferings.RESTURANTRESERVATIONOFFERINGS, "fk_ResturantReservationOfferings_Weekday", Resturantreservationofferings.RESTURANTRESERVATIONOFFERINGS.WEEKDAY);
        public static final ForeignKey<ResturantreservationofferingsRecord, ResturantsRecord> FK_RESTURANTRESERVATIONOFFERINGS_RESTURANTS = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_RESTURANTS_PRIMARY, Resturantreservationofferings.RESTURANTRESERVATIONOFFERINGS, "fk_ResturantReservationOfferings_Resturants", Resturantreservationofferings.RESTURANTRESERVATIONOFFERINGS.RESTURANTID);
        public static final ForeignKey<RoomofferingallocationsRecord, RoomofferingsRecord> FK_ROOMOFFERINGALLOCATION_ROOMOFFERING = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_ROOMOFFERINGS_PRIMARY, Roomofferingallocations.ROOMOFFERINGALLOCATIONS, "fk_RoomOfferingAllocation_RoomOffering", Roomofferingallocations.ROOMOFFERINGALLOCATIONS.ROOMOFFERINGID);
        public static final ForeignKey<RoomofferingrateoverridesRecord, RoomofferingsRecord> FK_ROOMOFFERINGRATEOVERRIDE_ROOMOFFERING = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_ROOMOFFERINGS_PRIMARY, Roomofferingrateoverrides.ROOMOFFERINGRATEOVERRIDES, "fk_RoomOfferingRateOverride_RoomOffering", Roomofferingrateoverrides.ROOMOFFERINGRATEOVERRIDES.ROOMOFFERINGID);
        public static final ForeignKey<RoomofferingratesRecord, RoomofferingsRecord> FK_ROOMOFFERINGRATE_ROOMOFFERING = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_ROOMOFFERINGS_PRIMARY, Roomofferingrates.ROOMOFFERINGRATES, "fk_RoomOfferingRate_RoomOffering", Roomofferingrates.ROOMOFFERINGRATES.ROOMOFFERINGID);
        public static final ForeignKey<RoomofferingsRecord, HotelsRecord> FK_ROOMOFFERING_HOTEL = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_HOTELS_PRIMARY, Roomofferings.ROOMOFFERINGS, "fk_RoomOffering_Hotel", Roomofferings.ROOMOFFERINGS.HOTELID);
        public static final ForeignKey<RoomofferingsRecord, RoomtypesRecord> FK_ROOMOFFERING_ROOMTYPE = createForeignKey(NewcastleConnections.packagedeals.Keys.KEY_ROOMTYPES_PRIMARY, Roomofferings.ROOMOFFERINGS, "fk_RoomOffering_RoomType", Roomofferings.ROOMOFFERINGS.ROOMTYPEID);
    }
}
