/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals;


import NewcastleConnections.DefaultCatalog;
import NewcastleConnections.packagedeals.tables.Experiencebookingoffering;
import NewcastleConnections.packagedeals.tables.Experienceofferingdates;
import NewcastleConnections.packagedeals.tables.Experienceofferingsdatetime;
import NewcastleConnections.packagedeals.tables.Experienceproviders;
import NewcastleConnections.packagedeals.tables.Experiences;
import NewcastleConnections.packagedeals.tables.Experiencevoucherofferings;
import NewcastleConnections.packagedeals.tables.Hotels;
import NewcastleConnections.packagedeals.tables.Invoiceexperience;
import NewcastleConnections.packagedeals.tables.Invoicehotel;
import NewcastleConnections.packagedeals.tables.Invoicerestaurant;
import NewcastleConnections.packagedeals.tables.Invoices;
import NewcastleConnections.packagedeals.tables.Invoicestatus;
import NewcastleConnections.packagedeals.tables.Resturantopeninghours;
import NewcastleConnections.packagedeals.tables.Resturantopeninghoursoverrides;
import NewcastleConnections.packagedeals.tables.Resturantreservationofferingoverrides;
import NewcastleConnections.packagedeals.tables.Resturantreservationofferings;
import NewcastleConnections.packagedeals.tables.Resturants;
import NewcastleConnections.packagedeals.tables.Roomofferingallocations;
import NewcastleConnections.packagedeals.tables.Roomofferingrateoverrides;
import NewcastleConnections.packagedeals.tables.Roomofferingrates;
import NewcastleConnections.packagedeals.tables.Roomofferings;
import NewcastleConnections.packagedeals.tables.Roomtypes;
import NewcastleConnections.packagedeals.tables.Tagallocations;
import NewcastleConnections.packagedeals.tables.Tags;
import NewcastleConnections.packagedeals.tables.Transport;
import NewcastleConnections.packagedeals.tables.Users;
import NewcastleConnections.packagedeals.tables.Weekday;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Packagedeals extends SchemaImpl {

    private static final long serialVersionUID = -290129248;

    /**
     * The reference instance of <code>PackageDeals</code>
     */
    public static final Packagedeals PACKAGEDEALS = new Packagedeals();

    /**
     * The table <code>PackageDeals.ExperienceBookingOffering</code>.
     */
    public final Experiencebookingoffering EXPERIENCEBOOKINGOFFERING = NewcastleConnections.packagedeals.tables.Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING;

    /**
     * The table <code>PackageDeals.ExperienceOfferingDates</code>.
     */
    public final Experienceofferingdates EXPERIENCEOFFERINGDATES = NewcastleConnections.packagedeals.tables.Experienceofferingdates.EXPERIENCEOFFERINGDATES;

    /**
     * The table <code>PackageDeals.ExperienceOfferingsDateTime</code>.
     */
    public final Experienceofferingsdatetime EXPERIENCEOFFERINGSDATETIME = NewcastleConnections.packagedeals.tables.Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME;

    /**
     * The table <code>PackageDeals.ExperienceProviders</code>.
     */
    public final Experienceproviders EXPERIENCEPROVIDERS = NewcastleConnections.packagedeals.tables.Experienceproviders.EXPERIENCEPROVIDERS;

    /**
     * The table <code>PackageDeals.Experiences</code>.
     */
    public final Experiences EXPERIENCES = NewcastleConnections.packagedeals.tables.Experiences.EXPERIENCES;

    /**
     * The table <code>PackageDeals.ExperienceVoucherOfferings</code>.
     */
    public final Experiencevoucherofferings EXPERIENCEVOUCHEROFFERINGS = NewcastleConnections.packagedeals.tables.Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS;

    /**
     * The table <code>PackageDeals.Hotels</code>.
     */
    public final Hotels HOTELS = NewcastleConnections.packagedeals.tables.Hotels.HOTELS;

    /**
     * The table <code>PackageDeals.InvoiceExperience</code>.
     */
    public final Invoiceexperience INVOICEEXPERIENCE = NewcastleConnections.packagedeals.tables.Invoiceexperience.INVOICEEXPERIENCE;

    /**
     * The table <code>PackageDeals.InvoiceHotel</code>.
     */
    public final Invoicehotel INVOICEHOTEL = NewcastleConnections.packagedeals.tables.Invoicehotel.INVOICEHOTEL;

    /**
     * The table <code>PackageDeals.InvoiceRestaurant</code>.
     */
    public final Invoicerestaurant INVOICERESTAURANT = NewcastleConnections.packagedeals.tables.Invoicerestaurant.INVOICERESTAURANT;

    /**
     * The table <code>PackageDeals.Invoices</code>.
     */
    public final Invoices INVOICES = NewcastleConnections.packagedeals.tables.Invoices.INVOICES;

    /**
     * The table <code>PackageDeals.InvoiceStatus</code>.
     */
    public final Invoicestatus INVOICESTATUS = NewcastleConnections.packagedeals.tables.Invoicestatus.INVOICESTATUS;

    /**
     * The table <code>PackageDeals.ResturantOpeningHours</code>.
     */
    public final Resturantopeninghours RESTURANTOPENINGHOURS = NewcastleConnections.packagedeals.tables.Resturantopeninghours.RESTURANTOPENINGHOURS;

    /**
     * The table <code>PackageDeals.ResturantOpeningHoursOverrides</code>.
     */
    public final Resturantopeninghoursoverrides RESTURANTOPENINGHOURSOVERRIDES = NewcastleConnections.packagedeals.tables.Resturantopeninghoursoverrides.RESTURANTOPENINGHOURSOVERRIDES;

    /**
     * The table <code>PackageDeals.ResturantReservationOfferingOverrides</code>.
     */
    public final Resturantreservationofferingoverrides RESTURANTRESERVATIONOFFERINGOVERRIDES = NewcastleConnections.packagedeals.tables.Resturantreservationofferingoverrides.RESTURANTRESERVATIONOFFERINGOVERRIDES;

    /**
     * The table <code>PackageDeals.ResturantReservationOfferings</code>.
     */
    public final Resturantreservationofferings RESTURANTRESERVATIONOFFERINGS = NewcastleConnections.packagedeals.tables.Resturantreservationofferings.RESTURANTRESERVATIONOFFERINGS;

    /**
     * The table <code>PackageDeals.Resturants</code>.
     */
    public final Resturants RESTURANTS = NewcastleConnections.packagedeals.tables.Resturants.RESTURANTS;

    /**
     * The table <code>PackageDeals.RoomOfferingAllocations</code>.
     */
    public final Roomofferingallocations ROOMOFFERINGALLOCATIONS = NewcastleConnections.packagedeals.tables.Roomofferingallocations.ROOMOFFERINGALLOCATIONS;

    /**
     * The table <code>PackageDeals.RoomOfferingRateOverrides</code>.
     */
    public final Roomofferingrateoverrides ROOMOFFERINGRATEOVERRIDES = NewcastleConnections.packagedeals.tables.Roomofferingrateoverrides.ROOMOFFERINGRATEOVERRIDES;

    /**
     * The table <code>PackageDeals.RoomOfferingRates</code>.
     */
    public final Roomofferingrates ROOMOFFERINGRATES = NewcastleConnections.packagedeals.tables.Roomofferingrates.ROOMOFFERINGRATES;

    /**
     * The table <code>PackageDeals.RoomOfferings</code>.
     */
    public final Roomofferings ROOMOFFERINGS = NewcastleConnections.packagedeals.tables.Roomofferings.ROOMOFFERINGS;

    /**
     * The table <code>PackageDeals.RoomTypes</code>.
     */
    public final Roomtypes ROOMTYPES = NewcastleConnections.packagedeals.tables.Roomtypes.ROOMTYPES;

    /**
     * The table <code>PackageDeals.TagAllocations</code>.
     */
    public final Tagallocations TAGALLOCATIONS = NewcastleConnections.packagedeals.tables.Tagallocations.TAGALLOCATIONS;

    /**
     * The table <code>PackageDeals.Tags</code>.
     */
    public final Tags TAGS = NewcastleConnections.packagedeals.tables.Tags.TAGS;

    /**
     * The table <code>PackageDeals.Transport</code>.
     */
    public final Transport TRANSPORT = NewcastleConnections.packagedeals.tables.Transport.TRANSPORT;

    /**
     * The table <code>PackageDeals.Users</code>.
     */
    public final Users USERS = NewcastleConnections.packagedeals.tables.Users.USERS;

    /**
     * The table <code>PackageDeals.Weekday</code>.
     */
    public final Weekday WEEKDAY = NewcastleConnections.packagedeals.tables.Weekday.WEEKDAY;

    /**
     * No further instances allowed
     */
    private Packagedeals() {
        super("PackageDeals", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING,
            Experienceofferingdates.EXPERIENCEOFFERINGDATES,
            Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME,
            Experienceproviders.EXPERIENCEPROVIDERS,
            Experiences.EXPERIENCES,
            Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS,
            Hotels.HOTELS,
            Invoiceexperience.INVOICEEXPERIENCE,
            Invoicehotel.INVOICEHOTEL,
            Invoicerestaurant.INVOICERESTAURANT,
            Invoices.INVOICES,
            Invoicestatus.INVOICESTATUS,
            Resturantopeninghours.RESTURANTOPENINGHOURS,
            Resturantopeninghoursoverrides.RESTURANTOPENINGHOURSOVERRIDES,
            Resturantreservationofferingoverrides.RESTURANTRESERVATIONOFFERINGOVERRIDES,
            Resturantreservationofferings.RESTURANTRESERVATIONOFFERINGS,
            Resturants.RESTURANTS,
            Roomofferingallocations.ROOMOFFERINGALLOCATIONS,
            Roomofferingrateoverrides.ROOMOFFERINGRATEOVERRIDES,
            Roomofferingrates.ROOMOFFERINGRATES,
            Roomofferings.ROOMOFFERINGS,
            Roomtypes.ROOMTYPES,
            Tagallocations.TAGALLOCATIONS,
            Tags.TAGS,
            Transport.TRANSPORT,
            Users.USERS,
            Weekday.WEEKDAY);
    }
}
