/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals;


import NewcastleConnections.packagedeals.tables.Experiencebookingoffering;
import NewcastleConnections.packagedeals.tables.Experienceofferingdates;
import NewcastleConnections.packagedeals.tables.Experienceofferingsdatetime;
import NewcastleConnections.packagedeals.tables.Experienceproviders;
import NewcastleConnections.packagedeals.tables.Experiences;
import NewcastleConnections.packagedeals.tables.Experiencevoucherofferings;
import NewcastleConnections.packagedeals.tables.Hotels;
import NewcastleConnections.packagedeals.tables.Invoiceexperience;
import NewcastleConnections.packagedeals.tables.Invoicehotel;
import NewcastleConnections.packagedeals.tables.Invoicerestaurant;
import NewcastleConnections.packagedeals.tables.Invoices;
import NewcastleConnections.packagedeals.tables.Invoicestatus;
import NewcastleConnections.packagedeals.tables.Resturantopeninghours;
import NewcastleConnections.packagedeals.tables.Resturantopeninghoursoverrides;
import NewcastleConnections.packagedeals.tables.Resturantreservationofferingoverrides;
import NewcastleConnections.packagedeals.tables.Resturantreservationofferings;
import NewcastleConnections.packagedeals.tables.Resturants;
import NewcastleConnections.packagedeals.tables.Roomofferingallocations;
import NewcastleConnections.packagedeals.tables.Roomofferingrateoverrides;
import NewcastleConnections.packagedeals.tables.Roomofferingrates;
import NewcastleConnections.packagedeals.tables.Roomofferings;
import NewcastleConnections.packagedeals.tables.Roomtypes;
import NewcastleConnections.packagedeals.tables.Tagallocations;
import NewcastleConnections.packagedeals.tables.Tags;
import NewcastleConnections.packagedeals.tables.Transport;
import NewcastleConnections.packagedeals.tables.Users;
import NewcastleConnections.packagedeals.tables.Weekday;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PackageDeals
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PackageDeals.ExperienceBookingOffering</code>.
     */
    public static final Experiencebookingoffering EXPERIENCEBOOKINGOFFERING = NewcastleConnections.packagedeals.tables.Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING;

    /**
     * The table <code>PackageDeals.ExperienceOfferingDates</code>.
     */
    public static final Experienceofferingdates EXPERIENCEOFFERINGDATES = NewcastleConnections.packagedeals.tables.Experienceofferingdates.EXPERIENCEOFFERINGDATES;

    /**
     * The table <code>PackageDeals.ExperienceOfferingsDateTime</code>.
     */
    public static final Experienceofferingsdatetime EXPERIENCEOFFERINGSDATETIME = NewcastleConnections.packagedeals.tables.Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME;

    /**
     * The table <code>PackageDeals.ExperienceProviders</code>.
     */
    public static final Experienceproviders EXPERIENCEPROVIDERS = NewcastleConnections.packagedeals.tables.Experienceproviders.EXPERIENCEPROVIDERS;

    /**
     * The table <code>PackageDeals.Experiences</code>.
     */
    public static final Experiences EXPERIENCES = NewcastleConnections.packagedeals.tables.Experiences.EXPERIENCES;

    /**
     * The table <code>PackageDeals.ExperienceVoucherOfferings</code>.
     */
    public static final Experiencevoucherofferings EXPERIENCEVOUCHEROFFERINGS = NewcastleConnections.packagedeals.tables.Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS;

    /**
     * The table <code>PackageDeals.Hotels</code>.
     */
    public static final Hotels HOTELS = NewcastleConnections.packagedeals.tables.Hotels.HOTELS;

    /**
     * The table <code>PackageDeals.InvoiceExperience</code>.
     */
    public static final Invoiceexperience INVOICEEXPERIENCE = NewcastleConnections.packagedeals.tables.Invoiceexperience.INVOICEEXPERIENCE;

    /**
     * The table <code>PackageDeals.InvoiceHotel</code>.
     */
    public static final Invoicehotel INVOICEHOTEL = NewcastleConnections.packagedeals.tables.Invoicehotel.INVOICEHOTEL;

    /**
     * The table <code>PackageDeals.InvoiceRestaurant</code>.
     */
    public static final Invoicerestaurant INVOICERESTAURANT = NewcastleConnections.packagedeals.tables.Invoicerestaurant.INVOICERESTAURANT;

    /**
     * The table <code>PackageDeals.Invoices</code>.
     */
    public static final Invoices INVOICES = NewcastleConnections.packagedeals.tables.Invoices.INVOICES;

    /**
     * The table <code>PackageDeals.InvoiceStatus</code>.
     */
    public static final Invoicestatus INVOICESTATUS = NewcastleConnections.packagedeals.tables.Invoicestatus.INVOICESTATUS;

    /**
     * The table <code>PackageDeals.ResturantOpeningHours</code>.
     */
    public static final Resturantopeninghours RESTURANTOPENINGHOURS = NewcastleConnections.packagedeals.tables.Resturantopeninghours.RESTURANTOPENINGHOURS;

    /**
     * The table <code>PackageDeals.ResturantOpeningHoursOverrides</code>.
     */
    public static final Resturantopeninghoursoverrides RESTURANTOPENINGHOURSOVERRIDES = NewcastleConnections.packagedeals.tables.Resturantopeninghoursoverrides.RESTURANTOPENINGHOURSOVERRIDES;

    /**
     * The table <code>PackageDeals.ResturantReservationOfferingOverrides</code>.
     */
    public static final Resturantreservationofferingoverrides RESTURANTRESERVATIONOFFERINGOVERRIDES = NewcastleConnections.packagedeals.tables.Resturantreservationofferingoverrides.RESTURANTRESERVATIONOFFERINGOVERRIDES;

    /**
     * The table <code>PackageDeals.ResturantReservationOfferings</code>.
     */
    public static final Resturantreservationofferings RESTURANTRESERVATIONOFFERINGS = NewcastleConnections.packagedeals.tables.Resturantreservationofferings.RESTURANTRESERVATIONOFFERINGS;

    /**
     * The table <code>PackageDeals.Resturants</code>.
     */
    public static final Resturants RESTURANTS = NewcastleConnections.packagedeals.tables.Resturants.RESTURANTS;

    /**
     * The table <code>PackageDeals.RoomOfferingAllocations</code>.
     */
    public static final Roomofferingallocations ROOMOFFERINGALLOCATIONS = NewcastleConnections.packagedeals.tables.Roomofferingallocations.ROOMOFFERINGALLOCATIONS;

    /**
     * The table <code>PackageDeals.RoomOfferingRateOverrides</code>.
     */
    public static final Roomofferingrateoverrides ROOMOFFERINGRATEOVERRIDES = NewcastleConnections.packagedeals.tables.Roomofferingrateoverrides.ROOMOFFERINGRATEOVERRIDES;

    /**
     * The table <code>PackageDeals.RoomOfferingRates</code>.
     */
    public static final Roomofferingrates ROOMOFFERINGRATES = NewcastleConnections.packagedeals.tables.Roomofferingrates.ROOMOFFERINGRATES;

    /**
     * The table <code>PackageDeals.RoomOfferings</code>.
     */
    public static final Roomofferings ROOMOFFERINGS = NewcastleConnections.packagedeals.tables.Roomofferings.ROOMOFFERINGS;

    /**
     * The table <code>PackageDeals.RoomTypes</code>.
     */
    public static final Roomtypes ROOMTYPES = NewcastleConnections.packagedeals.tables.Roomtypes.ROOMTYPES;

    /**
     * The table <code>PackageDeals.TagAllocations</code>.
     */
    public static final Tagallocations TAGALLOCATIONS = NewcastleConnections.packagedeals.tables.Tagallocations.TAGALLOCATIONS;

    /**
     * The table <code>PackageDeals.Tags</code>.
     */
    public static final Tags TAGS = NewcastleConnections.packagedeals.tables.Tags.TAGS;

    /**
     * The table <code>PackageDeals.Transport</code>.
     */
    public static final Transport TRANSPORT = NewcastleConnections.packagedeals.tables.Transport.TRANSPORT;

    /**
     * The table <code>PackageDeals.Users</code>.
     */
    public static final Users USERS = NewcastleConnections.packagedeals.tables.Users.USERS;

    /**
     * The table <code>PackageDeals.Weekday</code>.
     */
    public static final Weekday WEEKDAY = NewcastleConnections.packagedeals.tables.Weekday.WEEKDAY;
}
