/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables;


import NewcastleConnections.packagedeals.Keys;
import NewcastleConnections.packagedeals.Packagedeals;
import NewcastleConnections.packagedeals.tables.records.ExperiencevoucherofferingsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Experiencevoucherofferings extends TableImpl<ExperiencevoucherofferingsRecord> {

    private static final long serialVersionUID = 391375237;

    /**
     * The reference instance of <code>PackageDeals.ExperienceVoucherOfferings</code>
     */
    public static final Experiencevoucherofferings EXPERIENCEVOUCHEROFFERINGS = new Experiencevoucherofferings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExperiencevoucherofferingsRecord> getRecordType() {
        return ExperiencevoucherofferingsRecord.class;
    }

    /**
     * The column <code>PackageDeals.ExperienceVoucherOfferings.id</code>.
     */
    public final TableField<ExperiencevoucherofferingsRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceVoucherOfferings.guestCount</code>.
     */
    public final TableField<ExperiencevoucherofferingsRecord, UInteger> GUESTCOUNT = createField("guestCount", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceVoucherOfferings.price</code>.
     */
    public final TableField<ExperiencevoucherofferingsRecord, Double> PRICE = createField("price", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceVoucherOfferings.experienceId</code>.
     */
    public final TableField<ExperiencevoucherofferingsRecord, UInteger> EXPERIENCEID = createField("experienceId", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceVoucherOfferings.availableFrom</code>.
     */
    public final TableField<ExperiencevoucherofferingsRecord, Timestamp> AVAILABLEFROM = createField("availableFrom", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceVoucherOfferings.availableTo</code>.
     */
    public final TableField<ExperiencevoucherofferingsRecord, Timestamp> AVAILABLETO = createField("availableTo", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>PackageDeals.ExperienceVoucherOfferings</code> table reference
     */
    public Experiencevoucherofferings() {
        this("ExperienceVoucherOfferings", null);
    }

    /**
     * Create an aliased <code>PackageDeals.ExperienceVoucherOfferings</code> table reference
     */
    public Experiencevoucherofferings(String alias) {
        this(alias, EXPERIENCEVOUCHEROFFERINGS);
    }

    private Experiencevoucherofferings(String alias, Table<ExperiencevoucherofferingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Experiencevoucherofferings(String alias, Table<ExperiencevoucherofferingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Packagedeals.PACKAGEDEALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ExperiencevoucherofferingsRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_EXPERIENCEVOUCHEROFFERINGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ExperiencevoucherofferingsRecord> getPrimaryKey() {
        return Keys.KEY_EXPERIENCEVOUCHEROFFERINGS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ExperiencevoucherofferingsRecord>> getKeys() {
        return Arrays.<UniqueKey<ExperiencevoucherofferingsRecord>>asList(Keys.KEY_EXPERIENCEVOUCHEROFFERINGS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ExperiencevoucherofferingsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ExperiencevoucherofferingsRecord, ?>>asList(Keys.FK_EXPERIENCEVOUCHEROFFERINGS_EXPERIENCES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Experiencevoucherofferings as(String alias) {
        return new Experiencevoucherofferings(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Experiencevoucherofferings rename(String name) {
        return new Experiencevoucherofferings(name, null);
    }
}
