/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables;


import NewcastleConnections.packagedeals.Keys;
import NewcastleConnections.packagedeals.Packagedeals;
import NewcastleConnections.packagedeals.tables.records.ExperienceofferingdatesRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Experienceofferingdates extends TableImpl<ExperienceofferingdatesRecord> {

    private static final long serialVersionUID = 952696702;

    /**
     * The reference instance of <code>PackageDeals.ExperienceOfferingDates</code>
     */
    public static final Experienceofferingdates EXPERIENCEOFFERINGDATES = new Experienceofferingdates();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExperienceofferingdatesRecord> getRecordType() {
        return ExperienceofferingdatesRecord.class;
    }

    /**
     * The column <code>PackageDeals.ExperienceOfferingDates.id</code>.
     */
    public final TableField<ExperienceofferingdatesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceOfferingDates.experienceBookingOfferingId</code>.
     */
    public final TableField<ExperienceofferingdatesRecord, UInteger> EXPERIENCEBOOKINGOFFERINGID = createField("experienceBookingOfferingId", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceOfferingDates.date</code>.
     */
    public final TableField<ExperienceofferingdatesRecord, Date> DATE = createField("date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * Create a <code>PackageDeals.ExperienceOfferingDates</code> table reference
     */
    public Experienceofferingdates() {
        this("ExperienceOfferingDates", null);
    }

    /**
     * Create an aliased <code>PackageDeals.ExperienceOfferingDates</code> table reference
     */
    public Experienceofferingdates(String alias) {
        this(alias, EXPERIENCEOFFERINGDATES);
    }

    private Experienceofferingdates(String alias, Table<ExperienceofferingdatesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Experienceofferingdates(String alias, Table<ExperienceofferingdatesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Packagedeals.PACKAGEDEALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ExperienceofferingdatesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_EXPERIENCEOFFERINGDATES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ExperienceofferingdatesRecord> getPrimaryKey() {
        return Keys.KEY_EXPERIENCEOFFERINGDATES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ExperienceofferingdatesRecord>> getKeys() {
        return Arrays.<UniqueKey<ExperienceofferingdatesRecord>>asList(Keys.KEY_EXPERIENCEOFFERINGDATES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ExperienceofferingdatesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ExperienceofferingdatesRecord, ?>>asList(Keys.FK_EXPERIENCEOFFERINGDATES_EXPERIENCES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Experienceofferingdates as(String alias) {
        return new Experienceofferingdates(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Experienceofferingdates rename(String name) {
        return new Experienceofferingdates(name, null);
    }
}
