/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables;


import NewcastleConnections.packagedeals.Keys;
import NewcastleConnections.packagedeals.Packagedeals;
import NewcastleConnections.packagedeals.tables.records.ExperienceprovidersRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Experienceproviders extends TableImpl<ExperienceprovidersRecord> {

    private static final long serialVersionUID = -1401036600;

    /**
     * The reference instance of <code>PackageDeals.ExperienceProviders</code>
     */
    public static final Experienceproviders EXPERIENCEPROVIDERS = new Experienceproviders();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExperienceprovidersRecord> getRecordType() {
        return ExperienceprovidersRecord.class;
    }

    /**
     * The column <code>PackageDeals.ExperienceProviders.id</code>.
     */
    public final TableField<ExperienceprovidersRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceProviders.name</code>.
     */
    public final TableField<ExperienceprovidersRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceProviders.info</code>.
     */
    public final TableField<ExperienceprovidersRecord, String> INFO = createField("info", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceProviders.contact</code>.
     */
    public final TableField<ExperienceprovidersRecord, String> CONTACT = createField("contact", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceProviders.address</code>.
     */
    public final TableField<ExperienceprovidersRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceProviders.email</code>.
     */
    public final TableField<ExperienceprovidersRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceProviders.website</code>.
     */
    public final TableField<ExperienceprovidersRecord, String> WEBSITE = createField("website", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>PackageDeals.ExperienceProviders</code> table reference
     */
    public Experienceproviders() {
        this("ExperienceProviders", null);
    }

    /**
     * Create an aliased <code>PackageDeals.ExperienceProviders</code> table reference
     */
    public Experienceproviders(String alias) {
        this(alias, EXPERIENCEPROVIDERS);
    }

    private Experienceproviders(String alias, Table<ExperienceprovidersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Experienceproviders(String alias, Table<ExperienceprovidersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Packagedeals.PACKAGEDEALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ExperienceprovidersRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_EXPERIENCEPROVIDERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ExperienceprovidersRecord> getPrimaryKey() {
        return Keys.KEY_EXPERIENCEPROVIDERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ExperienceprovidersRecord>> getKeys() {
        return Arrays.<UniqueKey<ExperienceprovidersRecord>>asList(Keys.KEY_EXPERIENCEPROVIDERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Experienceproviders as(String alias) {
        return new Experienceproviders(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Experienceproviders rename(String name) {
        return new Experienceproviders(name, null);
    }
}
