/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables;


import NewcastleConnections.packagedeals.Keys;
import NewcastleConnections.packagedeals.Packagedeals;
import NewcastleConnections.packagedeals.tables.records.ExperiencebookingofferingRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Experiencebookingoffering extends TableImpl<ExperiencebookingofferingRecord> {

    private static final long serialVersionUID = 856291483;

    /**
     * The reference instance of <code>PackageDeals.ExperienceBookingOffering</code>
     */
    public static final Experiencebookingoffering EXPERIENCEBOOKINGOFFERING = new Experiencebookingoffering();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ExperiencebookingofferingRecord> getRecordType() {
        return ExperiencebookingofferingRecord.class;
    }

    /**
     * The column <code>PackageDeals.ExperienceBookingOffering.id</code>.
     */
    public final TableField<ExperiencebookingofferingRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceBookingOffering.pricePerGuest</code>.
     */
    public final TableField<ExperiencebookingofferingRecord, Double> PRICEPERGUEST = createField("pricePerGuest", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceBookingOffering.maxGuestsOrGuestCount</code>.
     */
    public final TableField<ExperiencebookingofferingRecord, Integer> MAXGUESTSORGUESTCOUNT = createField("maxGuestsOrGuestCount", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceBookingOffering.allowsVariableGuestCount</code>.
     */
    public final TableField<ExperiencebookingofferingRecord, Byte> ALLOWSVARIABLEGUESTCOUNT = createField("allowsVariableGuestCount", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.ExperienceBookingOffering.experienceId</code>.
     */
    public final TableField<ExperiencebookingofferingRecord, UInteger> EXPERIENCEID = createField("experienceId", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>PackageDeals.ExperienceBookingOffering</code> table reference
     */
    public Experiencebookingoffering() {
        this("ExperienceBookingOffering", null);
    }

    /**
     * Create an aliased <code>PackageDeals.ExperienceBookingOffering</code> table reference
     */
    public Experiencebookingoffering(String alias) {
        this(alias, EXPERIENCEBOOKINGOFFERING);
    }

    private Experiencebookingoffering(String alias, Table<ExperiencebookingofferingRecord> aliased) {
        this(alias, aliased, null);
    }

    private Experiencebookingoffering(String alias, Table<ExperiencebookingofferingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Packagedeals.PACKAGEDEALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ExperiencebookingofferingRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_EXPERIENCEBOOKINGOFFERING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ExperiencebookingofferingRecord> getPrimaryKey() {
        return Keys.KEY_EXPERIENCEBOOKINGOFFERING_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ExperiencebookingofferingRecord>> getKeys() {
        return Arrays.<UniqueKey<ExperiencebookingofferingRecord>>asList(Keys.KEY_EXPERIENCEBOOKINGOFFERING_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ExperiencebookingofferingRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ExperiencebookingofferingRecord, ?>>asList(Keys.FK_EXPERIENCEBOOKINGOFFERING_EXPERIENCES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Experiencebookingoffering as(String alias) {
        return new Experiencebookingoffering(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Experiencebookingoffering rename(String name) {
        return new Experiencebookingoffering(name, null);
    }
}
