/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables;


import NewcastleConnections.packagedeals.Keys;
import NewcastleConnections.packagedeals.Packagedeals;
import NewcastleConnections.packagedeals.tables.records.InvoicesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Invoices extends TableImpl<InvoicesRecord> {

    private static final long serialVersionUID = 1383226881;

    /**
     * The reference instance of <code>PackageDeals.Invoices</code>
     */
    public static final Invoices INVOICES = new Invoices();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InvoicesRecord> getRecordType() {
        return InvoicesRecord.class;
    }

    /**
     * The column <code>PackageDeals.Invoices.id</code>.
     */
    public final TableField<InvoicesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.Invoices.customerId</code>.
     */
    public final TableField<InvoicesRecord, String> CUSTOMERID = createField("customerId", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>PackageDeals.Invoices.purchaseDate</code>.
     */
    public final TableField<InvoicesRecord, Timestamp> PURCHASEDATE = createField("purchaseDate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.Invoices.price</code>.
     */
    public final TableField<InvoicesRecord, Double> PRICE = createField("price", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.Invoices.status</code>.
     */
    public final TableField<InvoicesRecord, UInteger> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>PackageDeals.Invoices</code> table reference
     */
    public Invoices() {
        this("Invoices", null);
    }

    /**
     * Create an aliased <code>PackageDeals.Invoices</code> table reference
     */
    public Invoices(String alias) {
        this(alias, INVOICES);
    }

    private Invoices(String alias, Table<InvoicesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Invoices(String alias, Table<InvoicesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Packagedeals.PACKAGEDEALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<InvoicesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_INVOICES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InvoicesRecord> getPrimaryKey() {
        return Keys.KEY_INVOICES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InvoicesRecord>> getKeys() {
        return Arrays.<UniqueKey<InvoicesRecord>>asList(Keys.KEY_INVOICES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Invoices as(String alias) {
        return new Invoices(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Invoices rename(String name) {
        return new Invoices(name, null);
    }
}
