/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables;


import NewcastleConnections.packagedeals.Keys;
import NewcastleConnections.packagedeals.Packagedeals;
import NewcastleConnections.packagedeals.tables.records.InvoicerestaurantRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Invoicerestaurant extends TableImpl<InvoicerestaurantRecord> {

    private static final long serialVersionUID = -1158343380;

    /**
     * The reference instance of <code>PackageDeals.InvoiceRestaurant</code>
     */
    public static final Invoicerestaurant INVOICERESTAURANT = new Invoicerestaurant();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InvoicerestaurantRecord> getRecordType() {
        return InvoicerestaurantRecord.class;
    }

    /**
     * The column <code>PackageDeals.InvoiceRestaurant.invoiceId</code>.
     */
    public final TableField<InvoicerestaurantRecord, UInteger> INVOICEID = createField("invoiceId", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.InvoiceRestaurant.restaurantId</code>.
     */
    public final TableField<InvoicerestaurantRecord, UInteger> RESTAURANTID = createField("restaurantId", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>PackageDeals.InvoiceRestaurant</code> table reference
     */
    public Invoicerestaurant() {
        this("InvoiceRestaurant", null);
    }

    /**
     * Create an aliased <code>PackageDeals.InvoiceRestaurant</code> table reference
     */
    public Invoicerestaurant(String alias) {
        this(alias, INVOICERESTAURANT);
    }

    private Invoicerestaurant(String alias, Table<InvoicerestaurantRecord> aliased) {
        this(alias, aliased, null);
    }

    private Invoicerestaurant(String alias, Table<InvoicerestaurantRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Packagedeals.PACKAGEDEALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InvoicerestaurantRecord> getPrimaryKey() {
        return Keys.KEY_INVOICERESTAURANT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InvoicerestaurantRecord>> getKeys() {
        return Arrays.<UniqueKey<InvoicerestaurantRecord>>asList(Keys.KEY_INVOICERESTAURANT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<InvoicerestaurantRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InvoicerestaurantRecord, ?>>asList(Keys.IRINVOICE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Invoicerestaurant as(String alias) {
        return new Invoicerestaurant(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Invoicerestaurant rename(String name) {
        return new Invoicerestaurant(name, null);
    }
}
