/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables;


import NewcastleConnections.packagedeals.Keys;
import NewcastleConnections.packagedeals.Packagedeals;
import NewcastleConnections.packagedeals.tables.records.InvoicehotelRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Invoicehotel extends TableImpl<InvoicehotelRecord> {

    private static final long serialVersionUID = -1504498114;

    /**
     * The reference instance of <code>PackageDeals.InvoiceHotel</code>
     */
    public static final Invoicehotel INVOICEHOTEL = new Invoicehotel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InvoicehotelRecord> getRecordType() {
        return InvoicehotelRecord.class;
    }

    /**
     * The column <code>PackageDeals.InvoiceHotel.invoiceId</code>.
     */
    public final TableField<InvoicehotelRecord, UInteger> INVOICEID = createField("invoiceId", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.InvoiceHotel.hotelId</code>.
     */
    public final TableField<InvoicehotelRecord, UInteger> HOTELID = createField("hotelId", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * Create a <code>PackageDeals.InvoiceHotel</code> table reference
     */
    public Invoicehotel() {
        this("InvoiceHotel", null);
    }

    /**
     * Create an aliased <code>PackageDeals.InvoiceHotel</code> table reference
     */
    public Invoicehotel(String alias) {
        this(alias, INVOICEHOTEL);
    }

    private Invoicehotel(String alias, Table<InvoicehotelRecord> aliased) {
        this(alias, aliased, null);
    }

    private Invoicehotel(String alias, Table<InvoicehotelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Packagedeals.PACKAGEDEALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<InvoicehotelRecord> getPrimaryKey() {
        return Keys.KEY_INVOICEHOTEL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<InvoicehotelRecord>> getKeys() {
        return Arrays.<UniqueKey<InvoicehotelRecord>>asList(Keys.KEY_INVOICEHOTEL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<InvoicehotelRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<InvoicehotelRecord, ?>>asList(Keys.IHINVOICE, Keys.IHHOTEL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Invoicehotel as(String alias) {
        return new Invoicehotel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Invoicehotel rename(String name) {
        return new Invoicehotel(name, null);
    }
}
