/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables;


import NewcastleConnections.packagedeals.Keys;
import NewcastleConnections.packagedeals.Packagedeals;
import NewcastleConnections.packagedeals.tables.records.RestaurantsRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Restaurants extends TableImpl<RestaurantsRecord> {

    private static final long serialVersionUID = -239757649;

    /**
     * The reference instance of <code>PackageDeals.Restaurants</code>
     */
    public static final Restaurants RESTAURANTS = new Restaurants();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RestaurantsRecord> getRecordType() {
        return RestaurantsRecord.class;
    }

    /**
     * The column <code>PackageDeals.Restaurants.id</code>.
     */
    public final TableField<RestaurantsRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.Restaurants.name</code>.
     */
    public final TableField<RestaurantsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.Restaurants.address</code>.
     */
    public final TableField<RestaurantsRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.Restaurants.contact</code>.
     */
    public final TableField<RestaurantsRecord, String> CONTACT = createField("contact", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>PackageDeals.Restaurants.email</code>.
     */
    public final TableField<RestaurantsRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>PackageDeals.Restaurants.website</code>.
     */
    public final TableField<RestaurantsRecord, String> WEBSITE = createField("website", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>PackageDeals.Restaurants.description</code>.
     */
    public final TableField<RestaurantsRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.Restaurants.hasWebMenu</code>.
     */
    public final TableField<RestaurantsRecord, Byte> HASWEBMENU = createField("hasWebMenu", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.Restaurants.allowsWebReservations</code>.
     */
    public final TableField<RestaurantsRecord, Byte> ALLOWSWEBRESERVATIONS = createField("allowsWebReservations", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.Restaurants.longitude</code>.
     */
    public final TableField<RestaurantsRecord, Double> LONGITUDE = createField("longitude", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.Restaurants.latitude</code>.
     */
    public final TableField<RestaurantsRecord, Double> LATITUDE = createField("latitude", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.Restaurants.imageID</code>.
     */
    public final TableField<RestaurantsRecord, String> IMAGEID = createField("imageID", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>PackageDeals.Restaurants.price</code>.
     */
    public final TableField<RestaurantsRecord, Double> PRICE = createField("price", org.jooq.impl.SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.Restaurants.category</code>.
     */
    public final TableField<RestaurantsRecord, String> CATEGORY = createField("category", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

    /**
     * The column <code>PackageDeals.Restaurants.publicallyVisible</code>.
     */
    public final TableField<RestaurantsRecord, Byte> PUBLICALLYVISIBLE = createField("publicallyVisible", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.Restaurants.releaseOnDate</code>.
     */
    public final TableField<RestaurantsRecord, Byte> RELEASEONDATE = createField("releaseOnDate", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>PackageDeals.Restaurants.releaseDate</code>.
     */
    public final TableField<RestaurantsRecord, Date> RELEASEDATE = createField("releaseDate", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * Create a <code>PackageDeals.Restaurants</code> table reference
     */
    public Restaurants() {
        this("Restaurants", null);
    }

    /**
     * Create an aliased <code>PackageDeals.Restaurants</code> table reference
     */
    public Restaurants(String alias) {
        this(alias, RESTAURANTS);
    }

    private Restaurants(String alias, Table<RestaurantsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Restaurants(String alias, Table<RestaurantsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Packagedeals.PACKAGEDEALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RestaurantsRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_RESTAURANTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RestaurantsRecord> getPrimaryKey() {
        return Keys.KEY_RESTAURANTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RestaurantsRecord>> getKeys() {
        return Arrays.<UniqueKey<RestaurantsRecord>>asList(Keys.KEY_RESTAURANTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Restaurants as(String alias) {
        return new Restaurants(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Restaurants rename(String name) {
        return new Restaurants(name, null);
    }
}
