/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables;


import NewcastleConnections.packagedeals.Keys;
import NewcastleConnections.packagedeals.Packagedeals;
import NewcastleConnections.packagedeals.tables.records.RoomtypesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Roomtypes extends TableImpl<RoomtypesRecord> {

    private static final long serialVersionUID = -1702971483;

    /**
     * The reference instance of <code>PackageDeals.RoomTypes</code>
     */
    public static final Roomtypes ROOMTYPES = new Roomtypes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoomtypesRecord> getRecordType() {
        return RoomtypesRecord.class;
    }

    /**
     * The column <code>PackageDeals.RoomTypes.id</code>.
     */
    public final TableField<RoomtypesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.RoomTypes.name</code>.
     */
    public final TableField<RoomtypesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>PackageDeals.RoomTypes.description</code>.
     */
    public final TableField<RoomtypesRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>PackageDeals.RoomTypes</code> table reference
     */
    public Roomtypes() {
        this("RoomTypes", null);
    }

    /**
     * Create an aliased <code>PackageDeals.RoomTypes</code> table reference
     */
    public Roomtypes(String alias) {
        this(alias, ROOMTYPES);
    }

    private Roomtypes(String alias, Table<RoomtypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Roomtypes(String alias, Table<RoomtypesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Packagedeals.PACKAGEDEALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RoomtypesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_ROOMTYPES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RoomtypesRecord> getPrimaryKey() {
        return Keys.KEY_ROOMTYPES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RoomtypesRecord>> getKeys() {
        return Arrays.<UniqueKey<RoomtypesRecord>>asList(Keys.KEY_ROOMTYPES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Roomtypes as(String alias) {
        return new Roomtypes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Roomtypes rename(String name) {
        return new Roomtypes(name, null);
    }
}
