/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Experiencebookingoffering;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperiencebookingofferingRecord extends UpdatableRecordImpl<ExperiencebookingofferingRecord> implements Record5<UInteger, Double, Integer, Byte, UInteger> {

    private static final long serialVersionUID = -1237312274;

    /**
     * Setter for <code>PackageDeals.ExperienceBookingOffering.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceBookingOffering.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceBookingOffering.pricePerGuest</code>.
     */
    public void setPriceperguest(Double value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceBookingOffering.pricePerGuest</code>.
     */
    public Double getPriceperguest() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceBookingOffering.maxGuestsOrGuestCount</code>.
     */
    public void setMaxguestsorguestcount(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceBookingOffering.maxGuestsOrGuestCount</code>.
     */
    public Integer getMaxguestsorguestcount() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceBookingOffering.allowsVariableGuestCount</code>.
     */
    public void setAllowsvariableguestcount(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceBookingOffering.allowsVariableGuestCount</code>.
     */
    public Byte getAllowsvariableguestcount() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceBookingOffering.experienceId</code>.
     */
    public void setExperienceid(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceBookingOffering.experienceId</code>.
     */
    public UInteger getExperienceid() {
        return (UInteger) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, Double, Integer, Byte, UInteger> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, Double, Integer, Byte, UInteger> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field2() {
        return Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING.PRICEPERGUEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING.MAXGUESTSORGUESTCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING.ALLOWSVARIABLEGUESTCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING.EXPERIENCEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value2() {
        return getPriceperguest();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMaxguestsorguestcount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getAllowsvariableguestcount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getExperienceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencebookingofferingRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencebookingofferingRecord value2(Double value) {
        setPriceperguest(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencebookingofferingRecord value3(Integer value) {
        setMaxguestsorguestcount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencebookingofferingRecord value4(Byte value) {
        setAllowsvariableguestcount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencebookingofferingRecord value5(UInteger value) {
        setExperienceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencebookingofferingRecord values(UInteger value1, Double value2, Integer value3, Byte value4, UInteger value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExperiencebookingofferingRecord
     */
    public ExperiencebookingofferingRecord() {
        super(Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING);
    }

    /**
     * Create a detached, initialised ExperiencebookingofferingRecord
     */
    public ExperiencebookingofferingRecord(UInteger id, Double priceperguest, Integer maxguestsorguestcount, Byte allowsvariableguestcount, UInteger experienceid) {
        super(Experiencebookingoffering.EXPERIENCEBOOKINGOFFERING);

        set(0, id);
        set(1, priceperguest);
        set(2, maxguestsorguestcount);
        set(3, allowsvariableguestcount);
        set(4, experienceid);
    }
}
