/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Experiences;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperiencesRecord extends UpdatableRecordImpl<ExperiencesRecord> implements Record16<UInteger, String, String, String, String, String, String, UInteger, Double, Double, String, Double, String, Byte, Byte, Date> {

    private static final long serialVersionUID = -1501403898;

    /**
     * Setter for <code>PackageDeals.Experiences.id</code>. On this table, if ‘allowsVariableGuestCount’ is true, then the user should be displayed with the option to select how many guests are present. This has to be inline with the ExperienceOfferings. If not, the experience should be for a set number of people, priced at maxGuests * pricePerGuest.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.id</code>. On this table, if ‘allowsVariableGuestCount’ is true, then the user should be displayed with the option to select how many guests are present. This has to be inline with the ExperienceOfferings. If not, the experience should be for a set number of people, priced at maxGuests * pricePerGuest.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.overview</code>.
     */
    public void setOverview(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.overview</code>.
     */
    public String getOverview() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.location</code>.
     */
    public void setLocation(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.location</code>.
     */
    public String getLocation() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.info</code>.
     */
    public void setInfo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.info</code>.
     */
    public String getInfo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.guidelines</code>.
     */
    public void setGuidelines(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.guidelines</code>.
     */
    public String getGuidelines() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.experienceProviderId</code>.
     */
    public void setExperienceproviderid(UInteger value) {
        set(7, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.experienceProviderId</code>.
     */
    public UInteger getExperienceproviderid() {
        return (UInteger) get(7);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.latitude</code>.
     */
    public void setLatitude(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.latitude</code>.
     */
    public Double getLatitude() {
        return (Double) get(8);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.longitude</code>.
     */
    public void setLongitude(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.longitude</code>.
     */
    public Double getLongitude() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.imageID</code>.
     */
    public void setImageid(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.imageID</code>.
     */
    public String getImageid() {
        return (String) get(10);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.price</code>.
     */
    public void setPrice(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.price</code>.
     */
    public Double getPrice() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.category</code>.
     */
    public void setCategory(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.category</code>.
     */
    public String getCategory() {
        return (String) get(12);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.publicallyVisible</code>.
     */
    public void setPublicallyvisible(Byte value) {
        set(13, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.publicallyVisible</code>.
     */
    public Byte getPublicallyvisible() {
        return (Byte) get(13);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.releaseOnDate</code>.
     */
    public void setReleaseondate(Byte value) {
        set(14, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.releaseOnDate</code>.
     */
    public Byte getReleaseondate() {
        return (Byte) get(14);
    }

    /**
     * Setter for <code>PackageDeals.Experiences.releaseDate</code>.
     */
    public void setReleasedate(Date value) {
        set(15, value);
    }

    /**
     * Getter for <code>PackageDeals.Experiences.releaseDate</code>.
     */
    public Date getReleasedate() {
        return (Date) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<UInteger, String, String, String, String, String, String, UInteger, Double, Double, String, Double, String, Byte, Byte, Date> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<UInteger, String, String, String, String, String, String, UInteger, Double, Double, String, Double, String, Byte, Byte, Date> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Experiences.EXPERIENCES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Experiences.EXPERIENCES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Experiences.EXPERIENCES.OVERVIEW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Experiences.EXPERIENCES.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Experiences.EXPERIENCES.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Experiences.EXPERIENCES.INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Experiences.EXPERIENCES.GUIDELINES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field8() {
        return Experiences.EXPERIENCES.EXPERIENCEPROVIDERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field9() {
        return Experiences.EXPERIENCES.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field10() {
        return Experiences.EXPERIENCES.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Experiences.EXPERIENCES.IMAGEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field12() {
        return Experiences.EXPERIENCES.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Experiences.EXPERIENCES.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field14() {
        return Experiences.EXPERIENCES.PUBLICALLYVISIBLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field15() {
        return Experiences.EXPERIENCES.RELEASEONDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field16() {
        return Experiences.EXPERIENCES.RELEASEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOverview();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getGuidelines();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value8() {
        return getExperienceproviderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value9() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value10() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getImageid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value12() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value14() {
        return getPublicallyvisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value15() {
        return getReleaseondate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value16() {
        return getReleasedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value3(String value) {
        setOverview(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value5(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value6(String value) {
        setInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value7(String value) {
        setGuidelines(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value8(UInteger value) {
        setExperienceproviderid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value9(Double value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value10(Double value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value11(String value) {
        setImageid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value12(Double value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value13(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value14(Byte value) {
        setPublicallyvisible(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value15(Byte value) {
        setReleaseondate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord value16(Date value) {
        setReleasedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencesRecord values(UInteger value1, String value2, String value3, String value4, String value5, String value6, String value7, UInteger value8, Double value9, Double value10, String value11, Double value12, String value13, Byte value14, Byte value15, Date value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExperiencesRecord
     */
    public ExperiencesRecord() {
        super(Experiences.EXPERIENCES);
    }

    /**
     * Create a detached, initialised ExperiencesRecord
     */
    public ExperiencesRecord(UInteger id, String name, String overview, String description, String location, String info, String guidelines, UInteger experienceproviderid, Double latitude, Double longitude, String imageid, Double price, String category, Byte publicallyvisible, Byte releaseondate, Date releasedate) {
        super(Experiences.EXPERIENCES);

        set(0, id);
        set(1, name);
        set(2, overview);
        set(3, description);
        set(4, location);
        set(5, info);
        set(6, guidelines);
        set(7, experienceproviderid);
        set(8, latitude);
        set(9, longitude);
        set(10, imageid);
        set(11, price);
        set(12, category);
        set(13, publicallyvisible);
        set(14, releaseondate);
        set(15, releasedate);
    }
}
