/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Experienceofferingsdatetime;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperienceofferingsdatetimeRecord extends UpdatableRecordImpl<ExperienceofferingsdatetimeRecord> implements Record4<UInteger, UInteger, Timestamp, UInteger> {

    private static final long serialVersionUID = -854267981;

    /**
     * Setter for <code>PackageDeals.ExperienceOfferingsDateTime.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceOfferingsDateTime.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceOfferingsDateTime.experienceOfferingDateId</code>.
     */
    public void setExperienceofferingdateid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceOfferingsDateTime.experienceOfferingDateId</code>.
     */
    public UInteger getExperienceofferingdateid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceOfferingsDateTime.time</code>.
     */
    public void setTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceOfferingsDateTime.time</code>.
     */
    public Timestamp getTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceOfferingsDateTime.maxGuestsAtTime</code>.
     */
    public void setMaxguestsattime(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceOfferingsDateTime.maxGuestsAtTime</code>.
     */
    public UInteger getMaxguestsattime() {
        return (UInteger) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, UInteger, Timestamp, UInteger> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, UInteger, Timestamp, UInteger> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME.EXPERIENCEOFFERINGDATEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME.MAXGUESTSATTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getExperienceofferingdateid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getMaxguestsattime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceofferingsdatetimeRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceofferingsdatetimeRecord value2(UInteger value) {
        setExperienceofferingdateid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceofferingsdatetimeRecord value3(Timestamp value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceofferingsdatetimeRecord value4(UInteger value) {
        setMaxguestsattime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceofferingsdatetimeRecord values(UInteger value1, UInteger value2, Timestamp value3, UInteger value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExperienceofferingsdatetimeRecord
     */
    public ExperienceofferingsdatetimeRecord() {
        super(Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME);
    }

    /**
     * Create a detached, initialised ExperienceofferingsdatetimeRecord
     */
    public ExperienceofferingsdatetimeRecord(UInteger id, UInteger experienceofferingdateid, Timestamp time, UInteger maxguestsattime) {
        super(Experienceofferingsdatetime.EXPERIENCEOFFERINGSDATETIME);

        set(0, id);
        set(1, experienceofferingdateid);
        set(2, time);
        set(3, maxguestsattime);
    }
}
