/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Experienceofferingdates;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperienceofferingdatesRecord extends UpdatableRecordImpl<ExperienceofferingdatesRecord> implements Record3<UInteger, UInteger, Date> {

    private static final long serialVersionUID = -1952440507;

    /**
     * Setter for <code>PackageDeals.ExperienceOfferingDates.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceOfferingDates.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceOfferingDates.experienceBookingOfferingId</code>.
     */
    public void setExperiencebookingofferingid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceOfferingDates.experienceBookingOfferingId</code>.
     */
    public UInteger getExperiencebookingofferingid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceOfferingDates.date</code>.
     */
    public void setDate(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceOfferingDates.date</code>.
     */
    public Date getDate() {
        return (Date) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, Date> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, UInteger, Date> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Experienceofferingdates.EXPERIENCEOFFERINGDATES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Experienceofferingdates.EXPERIENCEOFFERINGDATES.EXPERIENCEBOOKINGOFFERINGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Experienceofferingdates.EXPERIENCEOFFERINGDATES.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getExperiencebookingofferingid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceofferingdatesRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceofferingdatesRecord value2(UInteger value) {
        setExperiencebookingofferingid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceofferingdatesRecord value3(Date value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceofferingdatesRecord values(UInteger value1, UInteger value2, Date value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExperienceofferingdatesRecord
     */
    public ExperienceofferingdatesRecord() {
        super(Experienceofferingdates.EXPERIENCEOFFERINGDATES);
    }

    /**
     * Create a detached, initialised ExperienceofferingdatesRecord
     */
    public ExperienceofferingdatesRecord(UInteger id, UInteger experiencebookingofferingid, Date date) {
        super(Experienceofferingdates.EXPERIENCEOFFERINGDATES);

        set(0, id);
        set(1, experiencebookingofferingid);
        set(2, date);
    }
}
