/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Experienceproviders;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperienceprovidersRecord extends UpdatableRecordImpl<ExperienceprovidersRecord> implements Record7<UInteger, String, String, String, String, String, String> {

    private static final long serialVersionUID = 1920882489;

    /**
     * Setter for <code>PackageDeals.ExperienceProviders.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceProviders.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceProviders.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceProviders.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceProviders.info</code>.
     */
    public void setInfo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceProviders.info</code>.
     */
    public String getInfo() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceProviders.contact</code>.
     */
    public void setContact(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceProviders.contact</code>.
     */
    public String getContact() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceProviders.address</code>.
     */
    public void setAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceProviders.address</code>.
     */
    public String getAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceProviders.email</code>.
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceProviders.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceProviders.website</code>.
     */
    public void setWebsite(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceProviders.website</code>.
     */
    public String getWebsite() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Experienceproviders.EXPERIENCEPROVIDERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Experienceproviders.EXPERIENCEPROVIDERS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Experienceproviders.EXPERIENCEPROVIDERS.INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Experienceproviders.EXPERIENCEPROVIDERS.CONTACT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Experienceproviders.EXPERIENCEPROVIDERS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Experienceproviders.EXPERIENCEPROVIDERS.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Experienceproviders.EXPERIENCEPROVIDERS.WEBSITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getInfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContact();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceprovidersRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceprovidersRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceprovidersRecord value3(String value) {
        setInfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceprovidersRecord value4(String value) {
        setContact(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceprovidersRecord value5(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceprovidersRecord value6(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceprovidersRecord value7(String value) {
        setWebsite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceprovidersRecord values(UInteger value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExperienceprovidersRecord
     */
    public ExperienceprovidersRecord() {
        super(Experienceproviders.EXPERIENCEPROVIDERS);
    }

    /**
     * Create a detached, initialised ExperienceprovidersRecord
     */
    public ExperienceprovidersRecord(UInteger id, String name, String info, String contact, String address, String email, String website) {
        super(Experienceproviders.EXPERIENCEPROVIDERS);

        set(0, id);
        set(1, name);
        set(2, info);
        set(3, contact);
        set(4, address);
        set(5, email);
        set(6, website);
    }
}
