/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Experiencevoucherofferings;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExperiencevoucherofferingsRecord extends UpdatableRecordImpl<ExperiencevoucherofferingsRecord> implements Record6<UInteger, UInteger, Double, UInteger, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1434892800;

    /**
     * Setter for <code>PackageDeals.ExperienceVoucherOfferings.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceVoucherOfferings.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceVoucherOfferings.guestCount</code>.
     */
    public void setGuestcount(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceVoucherOfferings.guestCount</code>.
     */
    public UInteger getGuestcount() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceVoucherOfferings.price</code>.
     */
    public void setPrice(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceVoucherOfferings.price</code>.
     */
    public Double getPrice() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceVoucherOfferings.experienceId</code>.
     */
    public void setExperienceid(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceVoucherOfferings.experienceId</code>.
     */
    public UInteger getExperienceid() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceVoucherOfferings.availableFrom</code>.
     */
    public void setAvailablefrom(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceVoucherOfferings.availableFrom</code>.
     */
    public Timestamp getAvailablefrom() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>PackageDeals.ExperienceVoucherOfferings.availableTo</code>.
     */
    public void setAvailableto(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>PackageDeals.ExperienceVoucherOfferings.availableTo</code>.
     */
    public Timestamp getAvailableto() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, Double, UInteger, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, Double, UInteger, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS.GUESTCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS.EXPERIENCEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS.AVAILABLEFROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS.AVAILABLETO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getGuestcount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getExperienceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getAvailablefrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getAvailableto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencevoucherofferingsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencevoucherofferingsRecord value2(UInteger value) {
        setGuestcount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencevoucherofferingsRecord value3(Double value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencevoucherofferingsRecord value4(UInteger value) {
        setExperienceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencevoucherofferingsRecord value5(Timestamp value) {
        setAvailablefrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencevoucherofferingsRecord value6(Timestamp value) {
        setAvailableto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperiencevoucherofferingsRecord values(UInteger value1, UInteger value2, Double value3, UInteger value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ExperiencevoucherofferingsRecord
     */
    public ExperiencevoucherofferingsRecord() {
        super(Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS);
    }

    /**
     * Create a detached, initialised ExperiencevoucherofferingsRecord
     */
    public ExperiencevoucherofferingsRecord(UInteger id, UInteger guestcount, Double price, UInteger experienceid, Timestamp availablefrom, Timestamp availableto) {
        super(Experiencevoucherofferings.EXPERIENCEVOUCHEROFFERINGS);

        set(0, id);
        set(1, guestcount);
        set(2, price);
        set(3, experienceid);
        set(4, availablefrom);
        set(5, availableto);
    }
}
