/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Invoicehotel;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoicehotelRecord extends UpdatableRecordImpl<InvoicehotelRecord> implements Record7<UInteger, UInteger, Integer, Integer, Timestamp, Timestamp, Double> {

    private static final long serialVersionUID = 1743723287;

    /**
     * Setter for <code>PackageDeals.InvoiceHotel.invoiceId</code>.
     */
    public void setInvoiceid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.InvoiceHotel.invoiceId</code>.
     */
    public UInteger getInvoiceid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>PackageDeals.InvoiceHotel.roomId</code>.
     */
    public void setRoomid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.InvoiceHotel.roomId</code>.
     */
    public UInteger getRoomid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>PackageDeals.InvoiceHotel.adults</code>.
     */
    public void setAdults(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>PackageDeals.InvoiceHotel.adults</code>.
     */
    public Integer getAdults() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>PackageDeals.InvoiceHotel.children</code>.
     */
    public void setChildren(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PackageDeals.InvoiceHotel.children</code>.
     */
    public Integer getChildren() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PackageDeals.InvoiceHotel.checkIn</code>.
     */
    public void setCheckin(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>PackageDeals.InvoiceHotel.checkIn</code>.
     */
    public Timestamp getCheckin() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>PackageDeals.InvoiceHotel.checkOut</code>.
     */
    public void setCheckout(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>PackageDeals.InvoiceHotel.checkOut</code>.
     */
    public Timestamp getCheckout() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>PackageDeals.InvoiceHotel.price</code>.
     */
    public void setPrice(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>PackageDeals.InvoiceHotel.price</code>.
     */
    public Double getPrice() {
        return (Double) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, UInteger, Integer, Integer, Timestamp, Timestamp, Double> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UInteger, UInteger, Integer, Integer, Timestamp, Timestamp, Double> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Invoicehotel.INVOICEHOTEL.INVOICEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Invoicehotel.INVOICEHOTEL.ROOMID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Invoicehotel.INVOICEHOTEL.ADULTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Invoicehotel.INVOICEHOTEL.CHILDREN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Invoicehotel.INVOICEHOTEL.CHECKIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Invoicehotel.INVOICEHOTEL.CHECKOUT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return Invoicehotel.INVOICEHOTEL.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getInvoiceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getRoomid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getAdults();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getChildren();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCheckin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCheckout();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicehotelRecord value1(UInteger value) {
        setInvoiceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicehotelRecord value2(UInteger value) {
        setRoomid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicehotelRecord value3(Integer value) {
        setAdults(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicehotelRecord value4(Integer value) {
        setChildren(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicehotelRecord value5(Timestamp value) {
        setCheckin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicehotelRecord value6(Timestamp value) {
        setCheckout(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicehotelRecord value7(Double value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicehotelRecord values(UInteger value1, UInteger value2, Integer value3, Integer value4, Timestamp value5, Timestamp value6, Double value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoicehotelRecord
     */
    public InvoicehotelRecord() {
        super(Invoicehotel.INVOICEHOTEL);
    }

    /**
     * Create a detached, initialised InvoicehotelRecord
     */
    public InvoicehotelRecord(UInteger invoiceid, UInteger roomid, Integer adults, Integer children, Timestamp checkin, Timestamp checkout, Double price) {
        super(Invoicehotel.INVOICEHOTEL);

        set(0, invoiceid);
        set(1, roomid);
        set(2, adults);
        set(3, children);
        set(4, checkin);
        set(5, checkout);
        set(6, price);
    }
}
