/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Invoices;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoicesRecord extends UpdatableRecordImpl<InvoicesRecord> implements Record5<UInteger, String, Timestamp, Double, UInteger> {

    private static final long serialVersionUID = -350518220;

    /**
     * Setter for <code>PackageDeals.Invoices.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.Invoices.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>PackageDeals.Invoices.customerId</code>.
     */
    public void setCustomerid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.Invoices.customerId</code>.
     */
    public String getCustomerid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PackageDeals.Invoices.purchaseDate</code>.
     */
    public void setPurchasedate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>PackageDeals.Invoices.purchaseDate</code>.
     */
    public Timestamp getPurchasedate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>PackageDeals.Invoices.price</code>.
     */
    public void setPrice(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>PackageDeals.Invoices.price</code>.
     */
    public Double getPrice() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>PackageDeals.Invoices.status</code>.
     */
    public void setStatus(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>PackageDeals.Invoices.status</code>.
     */
    public UInteger getStatus() {
        return (UInteger) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, String, Timestamp, Double, UInteger> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, String, Timestamp, Double, UInteger> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Invoices.INVOICES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Invoices.INVOICES.CUSTOMERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Invoices.INVOICES.PURCHASEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Invoices.INVOICES.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return Invoices.INVOICES.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCustomerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getPurchasedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord value2(String value) {
        setCustomerid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord value3(Timestamp value) {
        setPurchasedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord value4(Double value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord value5(UInteger value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicesRecord values(UInteger value1, String value2, Timestamp value3, Double value4, UInteger value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoicesRecord
     */
    public InvoicesRecord() {
        super(Invoices.INVOICES);
    }

    /**
     * Create a detached, initialised InvoicesRecord
     */
    public InvoicesRecord(UInteger id, String customerid, Timestamp purchasedate, Double price, UInteger status) {
        super(Invoices.INVOICES);

        set(0, id);
        set(1, customerid);
        set(2, purchasedate);
        set(3, price);
        set(4, status);
    }
}
