/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Invoicerestaurant;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoicerestaurantRecord extends UpdatableRecordImpl<InvoicerestaurantRecord> implements Record5<UInteger, UInteger, Timestamp, Integer, Double> {

    private static final long serialVersionUID = 835635831;

    /**
     * Setter for <code>PackageDeals.InvoiceRestaurant.invoiceId</code>.
     */
    public void setInvoiceid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.InvoiceRestaurant.invoiceId</code>.
     */
    public UInteger getInvoiceid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>PackageDeals.InvoiceRestaurant.restaurantId</code>.
     */
    public void setRestaurantid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.InvoiceRestaurant.restaurantId</code>.
     */
    public UInteger getRestaurantid() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>PackageDeals.InvoiceRestaurant.time</code>.
     */
    public void setTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>PackageDeals.InvoiceRestaurant.time</code>.
     */
    public Timestamp getTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>PackageDeals.InvoiceRestaurant.seats</code>.
     */
    public void setSeats(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>PackageDeals.InvoiceRestaurant.seats</code>.
     */
    public Integer getSeats() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>PackageDeals.InvoiceRestaurant.voucherPrice</code>.
     */
    public void setVoucherprice(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>PackageDeals.InvoiceRestaurant.voucherPrice</code>.
     */
    public Double getVoucherprice() {
        return (Double) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, UInteger, Timestamp, Integer, Double> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, UInteger, Timestamp, Integer, Double> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Invoicerestaurant.INVOICERESTAURANT.INVOICEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Invoicerestaurant.INVOICERESTAURANT.RESTAURANTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Invoicerestaurant.INVOICERESTAURANT.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Invoicerestaurant.INVOICERESTAURANT.SEATS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Invoicerestaurant.INVOICERESTAURANT.VOUCHERPRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getInvoiceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getRestaurantid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSeats();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getVoucherprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicerestaurantRecord value1(UInteger value) {
        setInvoiceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicerestaurantRecord value2(UInteger value) {
        setRestaurantid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicerestaurantRecord value3(Timestamp value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicerestaurantRecord value4(Integer value) {
        setSeats(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicerestaurantRecord value5(Double value) {
        setVoucherprice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicerestaurantRecord values(UInteger value1, UInteger value2, Timestamp value3, Integer value4, Double value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoicerestaurantRecord
     */
    public InvoicerestaurantRecord() {
        super(Invoicerestaurant.INVOICERESTAURANT);
    }

    /**
     * Create a detached, initialised InvoicerestaurantRecord
     */
    public InvoicerestaurantRecord(UInteger invoiceid, UInteger restaurantid, Timestamp time, Integer seats, Double voucherprice) {
        super(Invoicerestaurant.INVOICERESTAURANT);

        set(0, invoiceid);
        set(1, restaurantid);
        set(2, time);
        set(3, seats);
        set(4, voucherprice);
    }
}
