/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Invoicerestaurant;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoicerestaurantRecord extends UpdatableRecordImpl<InvoicerestaurantRecord> implements Record2<UInteger, UInteger> {

    private static final long serialVersionUID = -2040321651;

    /**
     * Setter for <code>PackageDeals.InvoiceRestaurant.invoiceId</code>.
     */
    public void setInvoiceid(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.InvoiceRestaurant.invoiceId</code>.
     */
    public UInteger getInvoiceid() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>PackageDeals.InvoiceRestaurant.restaurantId</code>.
     */
    public void setRestaurantid(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.InvoiceRestaurant.restaurantId</code>.
     */
    public UInteger getRestaurantid() {
        return (UInteger) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, UInteger> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, UInteger> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Invoicerestaurant.INVOICERESTAURANT.INVOICEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Invoicerestaurant.INVOICERESTAURANT.RESTAURANTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getInvoiceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getRestaurantid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicerestaurantRecord value1(UInteger value) {
        setInvoiceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicerestaurantRecord value2(UInteger value) {
        setRestaurantid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InvoicerestaurantRecord values(UInteger value1, UInteger value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoicerestaurantRecord
     */
    public InvoicerestaurantRecord() {
        super(Invoicerestaurant.INVOICERESTAURANT);
    }

    /**
     * Create a detached, initialised InvoicerestaurantRecord
     */
    public InvoicerestaurantRecord(UInteger invoiceid, UInteger restaurantid) {
        super(Invoicerestaurant.INVOICERESTAURANT);

        set(0, invoiceid);
        set(1, restaurantid);
    }
}
