/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Restaurants;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RestaurantsRecord extends UpdatableRecordImpl<RestaurantsRecord> implements Record17<UInteger, String, String, String, String, String, String, Byte, Byte, Double, Double, String, Double, String, Byte, Byte, Date> {

    private static final long serialVersionUID = 835837964;

    /**
     * Setter for <code>PackageDeals.Restaurants.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.address</code>.
     */
    public void setAddress(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.address</code>.
     */
    public String getAddress() {
        return (String) get(2);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.contact</code>.
     */
    public void setContact(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.contact</code>.
     */
    public String getContact() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.website</code>.
     */
    public void setWebsite(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.website</code>.
     */
    public String getWebsite() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.hasWebMenu</code>.
     */
    public void setHaswebmenu(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.hasWebMenu</code>.
     */
    public Byte getHaswebmenu() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.allowsWebReservations</code>.
     */
    public void setAllowswebreservations(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.allowsWebReservations</code>.
     */
    public Byte getAllowswebreservations() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.longitude</code>.
     */
    public void setLongitude(Double value) {
        set(9, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.longitude</code>.
     */
    public Double getLongitude() {
        return (Double) get(9);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.latitude</code>.
     */
    public void setLatitude(Double value) {
        set(10, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.latitude</code>.
     */
    public Double getLatitude() {
        return (Double) get(10);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.imageID</code>.
     */
    public void setImageid(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.imageID</code>.
     */
    public String getImageid() {
        return (String) get(11);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.price</code>.
     */
    public void setPrice(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.price</code>.
     */
    public Double getPrice() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.category</code>.
     */
    public void setCategory(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.category</code>.
     */
    public String getCategory() {
        return (String) get(13);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.publicallyVisible</code>.
     */
    public void setPublicallyvisible(Byte value) {
        set(14, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.publicallyVisible</code>.
     */
    public Byte getPublicallyvisible() {
        return (Byte) get(14);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.releaseOnDate</code>.
     */
    public void setReleaseondate(Byte value) {
        set(15, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.releaseOnDate</code>.
     */
    public Byte getReleaseondate() {
        return (Byte) get(15);
    }

    /**
     * Setter for <code>PackageDeals.Restaurants.releaseDate</code>.
     */
    public void setReleasedate(Date value) {
        set(16, value);
    }

    /**
     * Getter for <code>PackageDeals.Restaurants.releaseDate</code>.
     */
    public Date getReleasedate() {
        return (Date) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<UInteger, String, String, String, String, String, String, Byte, Byte, Double, Double, String, Double, String, Byte, Byte, Date> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<UInteger, String, String, String, String, String, String, Byte, Byte, Double, Double, String, Double, String, Byte, Byte, Date> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Restaurants.RESTAURANTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Restaurants.RESTAURANTS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Restaurants.RESTAURANTS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Restaurants.RESTAURANTS.CONTACT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Restaurants.RESTAURANTS.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Restaurants.RESTAURANTS.WEBSITE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Restaurants.RESTAURANTS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return Restaurants.RESTAURANTS.HASWEBMENU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return Restaurants.RESTAURANTS.ALLOWSWEBRESERVATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field10() {
        return Restaurants.RESTAURANTS.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field11() {
        return Restaurants.RESTAURANTS.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Restaurants.RESTAURANTS.IMAGEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field13() {
        return Restaurants.RESTAURANTS.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Restaurants.RESTAURANTS.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field15() {
        return Restaurants.RESTAURANTS.PUBLICALLYVISIBLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field16() {
        return Restaurants.RESTAURANTS.RELEASEONDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field17() {
        return Restaurants.RESTAURANTS.RELEASEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getContact();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getHaswebmenu();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getAllowswebreservations();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value10() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value11() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getImageid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value13() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value15() {
        return getPublicallyvisible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value16() {
        return getReleaseondate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value17() {
        return getReleasedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value3(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value4(String value) {
        setContact(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value6(String value) {
        setWebsite(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value7(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value8(Byte value) {
        setHaswebmenu(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value9(Byte value) {
        setAllowswebreservations(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value10(Double value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value11(Double value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value12(String value) {
        setImageid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value13(Double value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value14(String value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value15(Byte value) {
        setPublicallyvisible(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value16(Byte value) {
        setReleaseondate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord value17(Date value) {
        setReleasedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RestaurantsRecord values(UInteger value1, String value2, String value3, String value4, String value5, String value6, String value7, Byte value8, Byte value9, Double value10, Double value11, String value12, Double value13, String value14, Byte value15, Byte value16, Date value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RestaurantsRecord
     */
    public RestaurantsRecord() {
        super(Restaurants.RESTAURANTS);
    }

    /**
     * Create a detached, initialised RestaurantsRecord
     */
    public RestaurantsRecord(UInteger id, String name, String address, String contact, String email, String website, String description, Byte haswebmenu, Byte allowswebreservations, Double longitude, Double latitude, String imageid, Double price, String category, Byte publicallyvisible, Byte releaseondate, Date releasedate) {
        super(Restaurants.RESTAURANTS);

        set(0, id);
        set(1, name);
        set(2, address);
        set(3, contact);
        set(4, email);
        set(5, website);
        set(6, description);
        set(7, haswebmenu);
        set(8, allowswebreservations);
        set(9, longitude);
        set(10, latitude);
        set(11, imageid);
        set(12, price);
        set(13, category);
        set(14, publicallyvisible);
        set(15, releaseondate);
        set(16, releasedate);
    }
}
