/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Roomofferingrates;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomofferingratesRecord extends UpdatableRecordImpl<RoomofferingratesRecord> implements Record9<UInteger, UInteger, UInteger, Double, Timestamp, Timestamp, Timestamp, Timestamp, UInteger> {

    private static final long serialVersionUID = -1396683707;

    /**
     * Setter for <code>PackageDeals.RoomOfferingRates.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferingRates.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferingRates.adultQty</code>.
     */
    public void setAdultqty(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferingRates.adultQty</code>.
     */
    public UInteger getAdultqty() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferingRates.childQty</code>.
     */
    public void setChildqty(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferingRates.childQty</code>.
     */
    public UInteger getChildqty() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferingRates.rate</code>.
     */
    public void setRate(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferingRates.rate</code>.
     */
    public Double getRate() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferingRates.appliesFrom</code>.
     */
    public void setAppliesfrom(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferingRates.appliesFrom</code>.
     */
    public Timestamp getAppliesfrom() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferingRates.appliedTo</code>.
     */
    public void setAppliedto(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferingRates.appliedTo</code>.
     */
    public Timestamp getAppliedto() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferingRates.validFrom</code>.
     */
    public void setValidfrom(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferingRates.validFrom</code>.
     */
    public Timestamp getValidfrom() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferingRates.validTo</code>.
     */
    public void setValidto(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferingRates.validTo</code>.
     */
    public Timestamp getValidto() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferingRates.roomOfferingId</code>.
     */
    public void setRoomofferingid(UInteger value) {
        set(8, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferingRates.roomOfferingId</code>.
     */
    public UInteger getRoomofferingid() {
        return (UInteger) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UInteger, UInteger, UInteger, Double, Timestamp, Timestamp, Timestamp, Timestamp, UInteger> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<UInteger, UInteger, UInteger, Double, Timestamp, Timestamp, Timestamp, Timestamp, UInteger> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Roomofferingrates.ROOMOFFERINGRATES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Roomofferingrates.ROOMOFFERINGRATES.ADULTQTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return Roomofferingrates.ROOMOFFERINGRATES.CHILDQTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return Roomofferingrates.ROOMOFFERINGRATES.RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Roomofferingrates.ROOMOFFERINGRATES.APPLIESFROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Roomofferingrates.ROOMOFFERINGRATES.APPLIEDTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Roomofferingrates.ROOMOFFERINGRATES.VALIDFROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Roomofferingrates.ROOMOFFERINGRATES.VALIDTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field9() {
        return Roomofferingrates.ROOMOFFERINGRATES.ROOMOFFERINGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getAdultqty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getChildqty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getRate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getAppliesfrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getAppliedto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getValidfrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getValidto();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value9() {
        return getRoomofferingid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingratesRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingratesRecord value2(UInteger value) {
        setAdultqty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingratesRecord value3(UInteger value) {
        setChildqty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingratesRecord value4(Double value) {
        setRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingratesRecord value5(Timestamp value) {
        setAppliesfrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingratesRecord value6(Timestamp value) {
        setAppliedto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingratesRecord value7(Timestamp value) {
        setValidfrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingratesRecord value8(Timestamp value) {
        setValidto(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingratesRecord value9(UInteger value) {
        setRoomofferingid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingratesRecord values(UInteger value1, UInteger value2, UInteger value3, Double value4, Timestamp value5, Timestamp value6, Timestamp value7, Timestamp value8, UInteger value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoomofferingratesRecord
     */
    public RoomofferingratesRecord() {
        super(Roomofferingrates.ROOMOFFERINGRATES);
    }

    /**
     * Create a detached, initialised RoomofferingratesRecord
     */
    public RoomofferingratesRecord(UInteger id, UInteger adultqty, UInteger childqty, Double rate, Timestamp appliesfrom, Timestamp appliedto, Timestamp validfrom, Timestamp validto, UInteger roomofferingid) {
        super(Roomofferingrates.ROOMOFFERINGRATES);

        set(0, id);
        set(1, adultqty);
        set(2, childqty);
        set(3, rate);
        set(4, appliesfrom);
        set(5, appliedto);
        set(6, validfrom);
        set(7, validto);
        set(8, roomofferingid);
    }
}
