/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Roomofferings;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomofferingsRecord extends UpdatableRecordImpl<RoomofferingsRecord> implements Record8<UInteger, UInteger, UInteger, UInteger, String, UInteger, UInteger, String> {

    private static final long serialVersionUID = 1563041061;

    /**
     * Setter for <code>PackageDeals.RoomOfferings.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferings.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferings.noGuestMax</code>.
     */
    public void setNoguestmax(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferings.noGuestMax</code>.
     */
    public UInteger getNoguestmax() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferings.noAdultMax</code>.
     */
    public void setNoadultmax(UInteger value) {
        set(2, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferings.noAdultMax</code>.
     */
    public UInteger getNoadultmax() {
        return (UInteger) get(2);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferings.noChildMax</code>.
     */
    public void setNochildmax(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferings.noChildMax</code>.
     */
    public UInteger getNochildmax() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferings.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferings.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferings.hotelId</code>.
     */
    public void setHotelid(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferings.hotelId</code>.
     */
    public UInteger getHotelid() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferings.roomTypeId</code>.
     */
    public void setRoomtypeid(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferings.roomTypeId</code>.
     */
    public UInteger getRoomtypeid() {
        return (UInteger) get(6);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferings.title</code>.
     */
    public void setTitle(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferings.title</code>.
     */
    public String getTitle() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UInteger, UInteger, UInteger, UInteger, String, UInteger, UInteger, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<UInteger, UInteger, UInteger, UInteger, String, UInteger, UInteger, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Roomofferings.ROOMOFFERINGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Roomofferings.ROOMOFFERINGS.NOGUESTMAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field3() {
        return Roomofferings.ROOMOFFERINGS.NOADULTMAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return Roomofferings.ROOMOFFERINGS.NOCHILDMAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Roomofferings.ROOMOFFERINGS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field6() {
        return Roomofferings.ROOMOFFERINGS.HOTELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return Roomofferings.ROOMOFFERINGS.ROOMTYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Roomofferings.ROOMOFFERINGS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getNoguestmax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value3() {
        return getNoadultmax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getNochildmax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value6() {
        return getHotelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getRoomtypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingsRecord value2(UInteger value) {
        setNoguestmax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingsRecord value3(UInteger value) {
        setNoadultmax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingsRecord value4(UInteger value) {
        setNochildmax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingsRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingsRecord value6(UInteger value) {
        setHotelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingsRecord value7(UInteger value) {
        setRoomtypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingsRecord value8(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingsRecord values(UInteger value1, UInteger value2, UInteger value3, UInteger value4, String value5, UInteger value6, UInteger value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoomofferingsRecord
     */
    public RoomofferingsRecord() {
        super(Roomofferings.ROOMOFFERINGS);
    }

    /**
     * Create a detached, initialised RoomofferingsRecord
     */
    public RoomofferingsRecord(UInteger id, UInteger noguestmax, UInteger noadultmax, UInteger nochildmax, String description, UInteger hotelid, UInteger roomtypeid, String title) {
        super(Roomofferings.ROOMOFFERINGS);

        set(0, id);
        set(1, noguestmax);
        set(2, noadultmax);
        set(3, nochildmax);
        set(4, description);
        set(5, hotelid);
        set(6, roomtypeid);
        set(7, title);
    }
}
