/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Roomofferingallocations;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoomofferingallocationsRecord extends UpdatableRecordImpl<RoomofferingallocationsRecord> implements Record5<UInteger, Timestamp, Timestamp, UInteger, UInteger> {

    private static final long serialVersionUID = -237327536;

    /**
     * Setter for <code>PackageDeals.RoomOfferingAllocations.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferingAllocations.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferingAllocations.fromDate</code>.
     */
    public void setFromdate(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferingAllocations.fromDate</code>.
     */
    public Timestamp getFromdate() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferingAllocations.toDate</code>.
     */
    public void setTodate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferingAllocations.toDate</code>.
     */
    public Timestamp getTodate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferingAllocations.quantity</code>.
     */
    public void setQuantity(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferingAllocations.quantity</code>.
     */
    public UInteger getQuantity() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>PackageDeals.RoomOfferingAllocations.roomOfferingId</code>.
     */
    public void setRoomofferingid(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>PackageDeals.RoomOfferingAllocations.roomOfferingId</code>.
     */
    public UInteger getRoomofferingid() {
        return (UInteger) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, Timestamp, Timestamp, UInteger, UInteger> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, Timestamp, Timestamp, UInteger, UInteger> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Roomofferingallocations.ROOMOFFERINGALLOCATIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Roomofferingallocations.ROOMOFFERINGALLOCATIONS.FROMDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Roomofferingallocations.ROOMOFFERINGALLOCATIONS.TODATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return Roomofferingallocations.ROOMOFFERINGALLOCATIONS.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return Roomofferingallocations.ROOMOFFERINGALLOCATIONS.ROOMOFFERINGID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getFromdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getTodate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getRoomofferingid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingallocationsRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingallocationsRecord value2(Timestamp value) {
        setFromdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingallocationsRecord value3(Timestamp value) {
        setTodate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingallocationsRecord value4(UInteger value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingallocationsRecord value5(UInteger value) {
        setRoomofferingid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoomofferingallocationsRecord values(UInteger value1, Timestamp value2, Timestamp value3, UInteger value4, UInteger value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoomofferingallocationsRecord
     */
    public RoomofferingallocationsRecord() {
        super(Roomofferingallocations.ROOMOFFERINGALLOCATIONS);
    }

    /**
     * Create a detached, initialised RoomofferingallocationsRecord
     */
    public RoomofferingallocationsRecord(UInteger id, Timestamp fromdate, Timestamp todate, UInteger quantity, UInteger roomofferingid) {
        super(Roomofferingallocations.ROOMOFFERINGALLOCATIONS);

        set(0, id);
        set(1, fromdate);
        set(2, todate);
        set(3, quantity);
        set(4, roomofferingid);
    }
}
