/*
 * This file is generated by jOOQ.
*/
package NewcastleConnections.packagedeals.tables.records;


import NewcastleConnections.packagedeals.tables.Tagallocations;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagallocationsRecord extends TableRecordImpl<TagallocationsRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 584892911;

    /**
     * Setter for <code>PackageDeals.TagAllocations.item</code>.
     */
    public void setItem(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>PackageDeals.TagAllocations.item</code>.
     */
    public Integer getItem() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PackageDeals.TagAllocations.tag</code>.
     */
    public void setTag(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>PackageDeals.TagAllocations.tag</code>.
     */
    public Integer getTag() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Tagallocations.TAGALLOCATIONS.ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Tagallocations.TAGALLOCATIONS.TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagallocationsRecord value1(Integer value) {
        setItem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagallocationsRecord value2(Integer value) {
        setTag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagallocationsRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagallocationsRecord
     */
    public TagallocationsRecord() {
        super(Tagallocations.TAGALLOCATIONS);
    }

    /**
     * Create a detached, initialised TagallocationsRecord
     */
    public TagallocationsRecord(Integer item, Integer tag) {
        super(Tagallocations.TAGALLOCATIONS);

        set(0, item);
        set(1, tag);
    }
}
